import {
  defineService,
  TenancyModule,
  CatalogModule,
  TenantCatalogModule,
  RetailersModule,
  PricingModule,
  InventoryModule,
  ProcurementModule,
  OrdersModule,
  ReceivablesModule,
  BillingModule,
  WarehouseModule,
  SyncModule,
  FilesModule,
  DeliveryModule,
  DocintModule,
  IntegrationsModule,
} from '@dos/core'

/** The back office shared by the manager and the accountant: approvals, orders, stock and GRNs, billing desk, receipts, registers, exports. */
export const service = defineService({
  name: 'manager',
  title: 'Manager service',
  defaultPort: 3002,
  roles: ['manager', 'accountant'],
  modules: [
    TenancyModule,
    CatalogModule,
    TenantCatalogModule,
    RetailersModule,
    PricingModule,
    InventoryModule,
    ProcurementModule,
    OrdersModule,
    ReceivablesModule,
    BillingModule,
    WarehouseModule,
    SyncModule,
    FilesModule,
    DeliveryModule,
    DocintModule,
    IntegrationsModule,
  ],
  contractKeys: [
    'health',
    'tenancy',
    'catalog',
    'tenantCatalog',
    'retailers',
    'pricing',
    'inventory',
    'procurement',
    'orders',
    'receivables',
    'billing',
    'warehouse',
    'sync',
    'files',
    'delivery',
    'docint',
    'integrations',
  ],
})
