import { sql } from 'drizzle-orm'
import {
  boolean,
  index,
  integer,
  jsonb,
  pgEnum,
  pgPolicy,
  pgTable,
  primaryKey,
  text,
  uniqueIndex,
} from 'drizzle-orm/pg-core'
import { id, timestamps, tz } from './columns.js'
import { appRw } from './roles.js'
import { users } from './tenancy.js'

/**
 * Identity. Better Auth's own tables (session, account, verification, organization...) are generated by its CLI
 * into a separate migration when the identity module lands; this file holds what the product needs around them.
 * These tables are global (keyed by user), not tenant tables.
 */

export const devicePlatform = pgEnum('device_platform', ['ios', 'android', 'web'])

/** A phone/browser a user signs in from; device_id is what sync_ops and GPS points are keyed by. */
export const devices = pgTable(
  'devices',
  {
    id: id(),
    userId: text('user_id')
      .notNull()
      .references(() => users.id),
    platform: devicePlatform('platform').notNull(),
    model: text('model'),
    osVersion: text('os_version'),
    appVersion: text('app_version'),
    /** PowerSync client id for staff devices. */
    syncClientId: text('sync_client_id'),
    lastSeenAt: tz('last_seen_at').notNull().defaultNow(),
    revokedAt: tz('revoked_at'),
    ...timestamps,
  },
  (t) => [
    index('devices_user_idx').on(t.userId),
    pgPolicy('devices_own', {
      for: 'all',
      to: appRw,
      using: sql`user_id = (SELECT current_setting('app.actor_id', true)) OR (SELECT current_setting('app.actor_role', true)) IN ('owner', 'manager', 'system')`,
      withCheck: sql`user_id = (SELECT current_setting('app.actor_id', true)) OR (SELECT current_setting('app.actor_role', true)) IN ('owner', 'manager', 'system')`,
    }),
  ],
).enableRLS()

/** DPDP: explicit, versioned consent for trip-scoped location tracking, per user per tenant. */
export const locationConsents = pgTable(
  'location_consents',
  {
    id: id(),
    userId: text('user_id')
      .notNull()
      .references(() => users.id),
    tenantId: text('tenant_id').notNull(),
    policyVersion: text('policy_version').notNull(),
    locale: text('locale').notNull(),
    granted: boolean('granted').notNull(),
    grantedAt: tz('granted_at').notNull().defaultNow(),
    withdrawnAt: tz('withdrawn_at'),
    evidence: jsonb('evidence'),
  },
  (t) => [
    index('location_consents_user_idx').on(t.userId, t.tenantId),
    pgPolicy('location_consents_rw', {
      for: 'all',
      to: appRw,
      using: sql`user_id = (SELECT current_setting('app.actor_id', true)) OR (tenant_id = (SELECT current_setting('app.tenant_id', true)) AND (SELECT current_setting('app.actor_role', true)) IN ('owner', 'manager', 'system'))`,
      withCheck: sql`user_id = (SELECT current_setting('app.actor_id', true)) OR (SELECT current_setting('app.actor_role', true)) = 'system'`,
    }),
  ],
).enableRLS()

/** OTP abuse control per phone and per IP; written only by the identity service (system role). */
export const otpRateLimits = pgTable(
  'otp_rate_limits',
  {
    key: text('key').notNull(),
    windowStart: tz('window_start').notNull(),
    attempts: integer('attempts').notNull().default(0),
    blockedUntil: tz('blocked_until'),
  },
  (t) => [
    primaryKey({ columns: [t.key, t.windowStart] }),
    uniqueIndex('otp_rate_limits_key_idx').on(t.key, t.windowStart),
    pgPolicy('otp_rate_limits_system', {
      for: 'all',
      to: appRw,
      using: sql`(SELECT current_setting('app.actor_role', true)) = 'system'`,
      withCheck: sql`(SELECT current_setting('app.actor_role', true)) = 'system'`,
    }),
  ],
).enableRLS()
