-- 0023 integrations wizard (generated by drizzle-kit from schema/integrations.ts; expand-only).
-- The three job_status values complete the import job's machine (importJobMachine in @dos/domain:
-- committed = applied and reversible, confirmed = signed off, rolled_back = reversed); they are added here
-- and first used from application code, never inside this transaction (coordination §2 rule 4).
-- import_jobs gains the dry-run snapshot, the sheet list and the confirm / rollback / cancel stamps;
-- import_rows gains the plan, the resolved ids, the candidates, the reviewer's overrides and the
-- before / effects snapshots a rollback restores from; import_profiles counts its uses.
ALTER TYPE "public"."job_status" ADD VALUE 'committed';--> statement-breakpoint
ALTER TYPE "public"."job_status" ADD VALUE 'confirmed';--> statement-breakpoint
ALTER TYPE "public"."job_status" ADD VALUE 'rolled_back';--> statement-breakpoint
ALTER TABLE "import_jobs" ADD COLUMN "sheet_names" jsonb;--> statement-breakpoint
ALTER TABLE "import_jobs" ADD COLUMN "dry_run" jsonb;--> statement-breakpoint
ALTER TABLE "import_jobs" ADD COLUMN "confirmed_at" timestamp with time zone;--> statement-breakpoint
ALTER TABLE "import_jobs" ADD COLUMN "confirmed_by" text;--> statement-breakpoint
ALTER TABLE "import_jobs" ADD COLUMN "rolled_back_at" timestamp with time zone;--> statement-breakpoint
ALTER TABLE "import_jobs" ADD COLUMN "rolled_back_by" text;--> statement-breakpoint
ALTER TABLE "import_jobs" ADD COLUMN "rollback_reason" text;--> statement-breakpoint
ALTER TABLE "import_jobs" ADD COLUMN "cancelled_at" timestamp with time zone;--> statement-breakpoint
ALTER TABLE "import_jobs" ADD COLUMN "cancel_reason" text;--> statement-breakpoint
ALTER TABLE "import_profiles" ADD COLUMN "used_count" integer DEFAULT 0 NOT NULL;--> statement-breakpoint
ALTER TABLE "import_rows" ADD COLUMN "plan" text;--> statement-breakpoint
ALTER TABLE "import_rows" ADD COLUMN "retailer_id" text;--> statement-breakpoint
ALTER TABLE "import_rows" ADD COLUMN "variant_id" text;--> statement-breakpoint
ALTER TABLE "import_rows" ADD COLUMN "candidates" jsonb DEFAULT '[]'::jsonb NOT NULL;--> statement-breakpoint
ALTER TABLE "import_rows" ADD COLUMN "overrides" jsonb;--> statement-breakpoint
ALTER TABLE "import_rows" ADD COLUMN "before" jsonb;--> statement-breakpoint
ALTER TABLE "import_rows" ADD COLUMN "effects" jsonb;--> statement-breakpoint
ALTER TABLE "import_jobs" ADD CONSTRAINT "import_jobs_confirmed_by_users_id_fk" FOREIGN KEY ("confirmed_by") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "import_jobs" ADD CONSTRAINT "import_jobs_rolled_back_by_users_id_fk" FOREIGN KEY ("rolled_back_by") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;