-- 0026 claims: cancel and cheque (generated by drizzle-kit from schema/claims.ts; expand-only).
-- The claims contract (claims.ts, slice 7) lets a DRAFT be discarded (`claims.cancel` → status `cancelled`,
-- never a numbered claim) and lets the brand settle by CHEQUE (Dr CHEQUES, the account code the receivables
-- ledger already carries); both values are added with ALTER TYPE … ADD VALUE (coordination §2 rule 4) and are
-- first USED by application code, never by a migration in this run. `claims_open_period_idx` is rebuilt so a
-- cancelled draft frees its (supplier, brand, kind, period) window for a re-open. Its predicate spells
-- "cancelled" as "no number and not a draft" (only a draft is ever cancelled, only a submit ever numbers)
-- because Postgres refuses an enum value inside the transaction that added it, drizzle's migrator applies
-- every pending migration in ONE transaction (fresh-database apply verified), and an `::text` cast is not
-- IMMUTABLE so it cannot appear in an index predicate at all.
ALTER TYPE "public"."claim_settlement_mode" ADD VALUE 'cheque';--> statement-breakpoint
ALTER TYPE "public"."claim_status" ADD VALUE 'cancelled';--> statement-breakpoint
DROP INDEX "claims_open_period_idx";--> statement-breakpoint
CREATE UNIQUE INDEX "claims_open_period_idx" ON "claims" USING btree ("tenant_id","supplier_id",coalesce(brand_id, ''),"kind","period_from","period_to") WHERE status <> 'rejected' AND (claim_no IS NOT NULL OR status = 'draft');