/**
 * This console's own string namespace, merged over the kit catalogue by `<ThemeProvider strings>`.
 *
 * English only for the pilot (founder, 2026-09-05) — and every user-visible word already has a locale
 * key, so Hindi and Marathi are a translation file, never a rewrite. No screen in this app contains a
 * literal English sentence.
 *
 * The voice is different here on purpose. The six distributor apps speak the trade's language to a
 * distributor. This one speaks OUR language about a distributor: "distributorship", "plan",
 * "support window", "the audit trail". It is also the only place the product's own name appears as
 * the chrome (docs/22 §9 item 10 — everywhere else the distributor's name and logo show).
 */
export const strings = {
  // --- frame ---------------------------------------------------------------
  'app.home': 'Platform',
  'app.signIn': 'Sign in',
  'app.signInTitle': 'Distribution OS console',
  'app.username': 'Username',
  'app.password': 'Password',
  'app.signInFailed': 'Could not sign in',
  'app.consoleOnly':
    'This console is for Distribution OS staff. A distributor signs in to their own app, never here.',
  'app.consoleSeparate':
    'A console account belongs to no distributorship, so there is nothing to pick after signing in.',
  'app.changePassword': 'Change your password',
  'app.passwordForced':
    'This password was given to you by someone else. Set your own before you carry on.',
  'app.passwordVoluntary': 'Choose a new password for this account.',
  'app.currentPassword': 'Current password',
  'app.newPassword': 'New password',
  'app.repeatPassword': 'New password again',
  'app.passwordRule': 'At least 8 characters, with a letter and a digit',
  'app.passwordMismatch': 'The two new passwords are not the same',
  'app.passwordNeedsCurrent': 'Enter the password you signed in with',
  'app.passwordRevokes': 'Your other devices will be signed out.',
  'app.setPassword': 'Set password',
  'app.passwordFailed': 'Could not change the password',
  'app.wrongApp': 'This sign-in is not a Distribution OS console account.',
  'app.wrongAppBody':
    'Only platform staff can open this console. Sign in to your distributor app instead.',
  'app.signOut': 'Sign out',

  // --- shared furniture ----------------------------------------------------
  'app.reload': 'Reload',
  'app.retry': 'Try again',
  'app.asOf': 'as of {when}',
  'app.showing': 'Showing {count}',
  'app.all': 'All',
  'app.open': 'Open',
  'app.cancel': 'Cancel',
  'app.search': 'Search',
  'app.days30': '30 days',
  'app.days60': '60 days',
  'app.days90': '90 days',
  'app.role': 'Role',
  'app.status': 'Status',
  'app.never': 'Never',
  /*
   * A READ that failed for want of a signal, said as a read.
   *
   * `@dos/api-client`'s default sentence for `kind: 'network'` is "No connection. This will send
   * when the signal is back." — true of a queued WRITE and false of every panel in this console,
   * which only ever asks. Measured with admin-service blocked: the Distributors register promised
   * to send something it was never given. `<Async>` wraps READS, so it says the read sentence; a
   * write keeps the client's own. (The warehouse and retailer gates found the same thing.)
   */
  'app.noConnectionRead': 'No connection. This is not the current picture.',
  'app.notLoaded': 'Not loaded',
  'app.countsOnly':
    'Counts only. Not one rupee of a distributor’s own trade is readable from this console.',

  // --- P1 platform overview ------------------------------------------------
  'p1.title': 'Platform',
  'p1.tenants': 'Distributorships',
  'p1.working': 'Working',
  'p1.suspended': 'Suspended',
  'p1.closed': 'Closed',
  'p1.activeUsers': 'People signed in this week',
  'p1.storage': 'Files stored',
  'p1.storageObjects': '{count} files',
  'p1.byPlan': 'Distributorships by plan',
  'p1.bySubscription': 'Subscriptions by state',
  'p1.work': 'Work going through the platform',
  'p1.orders': 'Orders a day',
  'p1.invoices': 'Bills a day',
  'p1.window': 'last {days} days',
  'p1.ordersWindow': '{count} orders in {days} days',
  'p1.invoicesWindow': '{count} bills in {days} days',
  'p1.openSubscriptions': 'Open Subscriptions',
  'p1.openSupport': 'Open Support access',
  'p1.plan': 'Plan',
  'p1.count': 'Distributorships',
  'p1.state': 'State',
  'p1.subscriptions': 'Subscriptions',
  'p1.needsAttention': 'Needs attention',
  'p1.pastDue': '{count} past due',
  'p1.trialEnding': '{count} trials ending in 30 days',
  'p1.waitingOwners': '{count} support requests waiting for an owner',
  'p1.allClear': 'Nothing waiting',

  // --- P2 distributors -----------------------------------------------------
  'p2.title': 'Distributors',
  'p2.searchPlaceholder': 'Name, handle or GSTIN',
  'p2.onboard': 'Onboard a distributor',
  'p2.name': 'Distributorship',
  'p2.handle': 'Handle',
  'p2.stateCode': 'State',
  'p2.plan': 'Plan',
  'p2.status': 'Status',
  'p2.subscription': 'Subscription',
  'p2.staff': 'Staff',
  'p2.shops': 'Shops',
  'p2.orders30d': 'Orders, 30 days',
  'p2.ordersUnit': 'orders',
  'p2.lastActivity': 'Last seen',
  'p2.since': 'On the platform since',
  'p2.empty': 'No distributorship matches',
  'p2.noSubscription': 'No subscription',

  // --- P3 onboard ----------------------------------------------------------
  'p3.title': 'Onboard a distributor',
  'p3.intro':
    'One call creates the distributorship, its chart of accounts, locations and invoice series, its first owner login and a trial. It is the only place in the product that creates one.',
  'p3.business': 'The business',
  'p3.legalName': 'Legal name',
  'p3.legalNameHelp': 'Exactly as it is written on their GST certificate',
  'p3.handle': 'Handle',
  'p3.handleHelp': 'Lowercase letters, digits and hyphens. It never changes.',
  'p3.gstin': 'GSTIN',
  'p3.gstinHelp': 'Optional. Checked here before it is sent.',
  'p3.gstinBad': 'That is not a valid GSTIN',
  'p3.gstinState': 'The GSTIN says {state}',
  'p3.state': 'State',
  'p3.plan': 'Plan',
  'p3.owner': 'Their first owner login',
  'p3.ownerHelp':
    'Read the temporary password out to them on the handover call. They must change it before anything else opens.',
  'p3.ownerName': 'Owner’s name',
  'p3.ownerUsername': 'Username',
  'p3.ownerPhone': 'Mobile number',
  'p3.ownerPhoneHelp': 'Ten digits, or +91 and ten digits',
  'p3.temporaryPassword': 'Temporary password',
  'p3.suggest': 'Suggest one',
  'p3.subscription': 'What they pay us',
  'p3.trialDays': 'Trial, in days',
  'p3.price': 'Price per period',
  'p3.interval': 'Billed',
  'p3.seats': 'Staff logins included',
  'p3.seatsHelp': 'Leave empty for a plan that does not cap them',
  'p3.create': 'Onboard this distributor',
  'p3.creating': 'Creating the distributorship',
  'p3.needName': 'Enter the legal name',
  'p3.needHandle': 'Enter a handle',
  'p3.needState': 'Pick a state',
  'p3.needOwner': 'Fill in the owner’s name, username and mobile number',
  'p3.needPassword': 'Set a temporary password of at least 8 characters with a letter and a digit',
  'p3.doneTitle': '{name} is on the platform',
  'p3.doneBody':
    'Hand these over on the call. The password is temporary: the owner is made to change it before anything else opens.',
  'p3.doneUsername': 'Owner username',
  'p3.donePassword': 'Temporary password',
  'p3.doneOpen': 'Open the distributorship',
  'p3.doneAnother': 'Onboard another',
  'p3.failed': 'Could not onboard this distributor',
  'p3.superOnly':
    'Onboarding a distributor needs a super administrator. Your console level reads the distributors; ask a super administrator to onboard this one.',
  'p3.superOnlyBack': 'Back to distributors',

  // --- P4 one distributor --------------------------------------------------
  'p4.size': 'How big they are',
  'p4.staff': 'Staff logins',
  'p4.shops': 'Shops',
  'p4.orders30d': 'Orders, 30 days',
  'p4.invoices30d': 'Bills, 30 days',
  'p4.storage': 'Files stored',
  'p4.lastActivity': 'Last seen',
  'p4.identity': 'Who they are',
  'p4.gstin': 'GSTIN',
  'p4.stateName': 'State',
  'p4.handle': 'Handle',
  'p4.onPlatform': 'On the platform since',
  'p4.subscription': 'Subscription',
  'p4.editSubscription': 'Change the plan',
  'p4.suspend': 'Suspend this distributorship',
  'p4.suspendTitle': 'Suspend {name}?',
  'p4.suspendBody':
    'Every sign-in to {name} is refused from the next token refresh. Nothing is deleted, and reactivating puts it back exactly as it was.',
  'p4.suspendReason': 'Why (goes into the audit trail)',
  'p4.suspendNeedsReason': 'Say why. This stops their work.',
  'p4.reactivate': 'Let them back in',
  'p4.reactivateTitle': 'Reactivate {name}?',
  'p4.reactivateBody': 'Sign-in starts working again from the next attempt.',
  'p4.reactivateNote': 'Note (optional)',
  'p4.suspendedSince': 'Suspended. Every sign-in to this distributorship is refused.',
  'p4.closedNotice': 'Closed. The relationship has ended; nothing has been deleted.',
  'p4.inside': 'Inside this distributorship',
  'p4.subscriptionChip': 'Subscription · {state}',
  'p4.insideLapsed':
    'Our last ask lapsed at {when} without an answer, so it can no longer be opened. Ask again.',
  'p4.insideShut':
    'Nothing of their trade is readable. Ask their owner for a time-boxed window and they decide.',
  'p4.insideAsk': 'Ask for support access',
  'p4.insideWaiting':
    'Asked at {when}. {name} is waiting for their owner to answer, in their own app.',
  'p4.insideOpen': 'A window is open until {when}, {scope}.',
  'p4.insideOpenDoor': 'Open the window',
  'p4.insideClosing': 'Opening the window',
  'p4.insideReadOnly': 'read only',
  'p4.insideReadWrite': 'read and write',
  'p4.insideProof': 'Read through the window',
  'p4.insideProofBody': 'Their service answered as their owner. Every call is in the audit trail.',
  'p4.insideDisplayName': 'The name they show their shops',
  'p4.insideSeries': 'Their invoice numbering, as their own service reports it',
  'p4.insideNextNo': 'next {no}',
  'p4.insideReadOnlyNote':
    'Read only: their service refuses a write from this window, and says so with a 403.',
  'p4.insidePassCloses': 'This read pass closes',
  'p4.insideHandBack': 'Hand the window back',
  'p4.insideAudit': 'What we have read under this window',
  'p4.insideNoReads': 'Nothing read yet under this window',
  'p4.insideFailed': 'Their service refused this window',

  // --- P5 subscriptions ----------------------------------------------------
  'p5.title': 'Subscriptions',
  'p5.distributor': 'Distributorship',
  'p5.plan': 'Plan',
  'p5.state': 'State',
  'p5.price': 'Price ₹',
  'p5.interval': 'Billed',
  'p5.seats': 'Seats',
  'p5.period': 'This period',
  'p5.renews': 'Renews',
  'p5.trialEnds': 'Trial ends',
  'p5.note': 'Note',
  'p5.empty': 'No subscription matches',
  'p5.endingSoon': 'Ending within 30 days',
  'p5.edit': 'Change the plan',
  'p5.editTitle': 'Subscription — {name}',
  'p5.save': 'Save the subscription',
  'p5.saved': 'Saved',
  'p5.failed': 'Could not save the subscription',
  'p5.periodStart': 'Period starts',
  'p5.periodEnd': 'Period ends',
  'p5.dateFormat': 'Year, month, day — 2026-09-06',
  'p5.dateOptional': 'Leave empty if there is no trial',
  'p5.dateWrong': 'A date has to read 2026-09-06 — year, month, day',
  'p5.trialEnded': 'Trial ended',
  'p5.ourPrice': 'This is OUR price to the distributor, never their price to a shop.',

  // --- P6 support access ---------------------------------------------------
  'p6.title': 'Support access',
  'p6.intro':
    'The console can only ask. The distributor’s own owner opens the window, in their own app, and it closes by itself. Every call made under a window is written to the audit trail.',
  'p6.ask': 'Ask for a window',
  'p6.askTitle': 'Ask {name} for support access',
  'p6.distributor': 'Distributorship',
  'p6.reason': 'Why (their owner reads this word for word)',
  'p6.reasonHelp': 'At least 10 characters. It is the whole basis of their decision.',
  'p6.reasonShort': 'Say why, in a sentence their owner can act on',
  'p6.scope': 'Scope',
  'p6.hours': 'Hours',
  'p6.send': 'Ask their owner',
  'p6.sending': 'Asking',
  'p6.sent': 'Asked. Their owner decides.',
  'p6.failed': 'Could not ask for access',
  'p6.pickDistributor': 'Pick a distributorship first',
  'p6.state': 'State',
  'p6.asked': 'Asked',
  'p6.askedBy': 'Asked by',
  'p6.decided': 'Answered',
  'p6.expires': 'Closes',
  'p6.expired': 'Closed {when}',
  'p6.closesIn': 'Closes in {when}',
  'p6.openNow': 'Open now',
  'p6.withdraw': 'Withdraw',
  'p6.handBack': 'Hand it back',
  'p6.withdrawTitle': 'Withdraw this request?',
  'p6.withdrawBody':
    'The request disappears from their owner’s app. Nothing was open, so nothing closes.',
  'p6.handBackTitle': 'Hand this window back?',
  'p6.handBackBody':
    'The window shuts at once, before it was due to. Ask again if there is more to do.',
  'p6.handBackReason': 'Note (optional)',
  'p6.empty': 'No support request matches',
  'p6.onlyOpen': 'Open now',
  'p6.decisionNote': 'Their note',
  'p6.revokeReason': 'Closing note',
  'p6.deniedByOwner': 'Their owner said no',
  'p6.lapsed': 'Lapsed, no answer',
  'p6.handedBack': 'Handed back from the Distribution OS console.',
  'p6.emptyOpen': 'No window is open right now',
  'p6.emptyWaiting': 'Nobody’s owner is being waited on',
  'p6.lapsedNote':
    'A request can only be opened inside the hours it asked for, counted from when it was made. This one ran out; raise a new request.',

  // --- P7 people -----------------------------------------------------------
  'p7.title': 'People',
  'p7.intro':
    'One phone, one login, however many distributorships it belongs to. This is the only place in the product where that list exists — no distributor may learn that a phone appears in another one’s network.',
  'p7.searchPlaceholder': 'Name, username or mobile number',
  'p7.name': 'Name',
  'p7.username': 'Username',
  'p7.phone': 'Mobile',
  'p7.status': 'Status',
  'p7.memberships': 'Distributorships',
  'p7.lastLogin': 'Last signed in',
  'p7.platformOnly': 'Our own staff',
  'p7.locked': 'Locked until {when}',
  'p7.mustChange': 'Temporary password',
  'p7.noUsername': 'No sign-in name yet',
  'p7.empty': 'Nobody matches',
  'p7.membershipsIn': 'Member of',
  'p7.disable': 'Lock this login',
  'p7.disableTitle': 'Lock {name} out?',
  'p7.disableBody':
    'This login stops working in every distributorship at once and every open session is ended. It does not remove them from any distributorship — that is their own owner’s to do. Nothing in this console puts it back.',
  'p7.disableReason': 'Why (goes into the audit trail)',
  'p7.disableNeedsReason': 'Say why. This locks them out everywhere.',
  'p7.disabled': 'Locked out',
  'p7.failed': 'Could not lock this login',
  'p7.membershipCount': '{count} distributorships',
  'p7.membershipOne': '1 distributorship',
  'p7.membershipNone': 'No distributorship',

  // --- P8 audit ------------------------------------------------------------
  'p8.title': 'Audit trail',
  'p8.intro':
    'Every platform action: onboarding, suspension, plans, support windows and what was read through them, and locked logins.',
  'p8.when': 'When',
  'p8.who': 'Who',
  'p8.action': 'What',
  'p8.distributor': 'Distributorship',
  'p8.entity': 'On',
  'p8.before': 'Before',
  'p8.after': 'After',
  'p8.empty': 'Nothing in this window',
  'p8.platformOnly': 'Platform actions only',
  'p8.detail': 'The entry',

  // --- P9 account ----------------------------------------------------------
  'p9.title': 'Account',
  'p9.you': 'You',
  'p9.name': 'Name',
  'p9.username': 'Username',
  'p9.roleLabel': 'Level',
  'p9.devices': 'Devices signed in as you',
  'p9.thisDevice': 'This device',
  'p9.signedIn': 'signed in {when}',
  'p9.lastUsed': 'last used {when}',
  'p9.endSession': 'End this session',
  'p9.noDevices': 'No other device is signed in',
  'p9.unnamedDevice': 'A device that gave no name',
  'p9.changePassword': 'Change your password',
  'p9.about': 'About',
  'p9.aboutBody':
    'Distribution OS console. Signs in at auth-service, reads admin-service, and reaches a distributor’s own service only through a window their owner opened.',

  // --- machine words -> the trade's own word (kit falls back to humanising) --
  'word.pilot': 'Pilot',
  'word.starter': 'Starter',
  'word.growth': 'Growth',
  'word.standard': 'Standard',
  'word.pro': 'Pro',
  'word.trialing': 'On trial',
  'word.active': 'Active',
  'word.past_due': 'Past due',
  'word.suspended': 'Suspended',
  'word.cancelled': 'Cancelled',
  'word.closed': 'Closed',
  'word.monthly': 'Monthly',
  'word.quarterly': 'Quarterly',
  'word.yearly': 'Yearly',
  'word.requested': 'Waiting for their owner',
  'word.approved': 'Open',
  'word.rejected': 'Refused',
  'word.revoked': 'Handed back',
  'word.expired': 'Closed',
  'word.read_only': 'Read only',
  'word.read_write': 'Read and write',
  'word.platform_admin': 'Distribution OS staff',
  'word.owner': 'Owner',
  'word.manager': 'Manager',
  'word.accountant': 'Accountant',
  'word.salesperson': 'Salesperson',
  'word.warehouse': 'Warehouse',
  'word.delivery': 'Delivery',
  'word.retailer': 'Shopkeeper',
  'word.invited': 'Invited',
  'word.disabled': 'Locked out',
  'word.web': 'Web',
  'word.android': 'Android',
  'word.ios': 'iPhone',
  'word.super': 'Super',
  'word.support': 'Support',
  'word.billing': 'Billing',
  'word.tenant.created': 'Distributorship created',
  'word.tenant.suspended': 'Distributorship suspended',
  'word.tenant.reactivated': 'Distributorship reactivated',
  'word.subscription.created': 'Subscription created',
  'word.subscription.updated': 'Subscription changed',
  'word.support.requested': 'Support access asked for',
  'word.support.revoked': 'Support window handed back',
  'word.support.read': 'Read under a support window',
  'word.support.approve': 'Support window opened',
  'word.user.disabled': 'Login locked',
  'word.yes': 'Yes',
} as const
