import {
  defineService,
  TenancyModule,
  CatalogModule,
  TenantCatalogModule,
  RetailersModule,
  PricingModule,
  InventoryModule,
  ProcurementModule,
  OrdersModule,
  ReceivablesModule,
  BillingModule,
  WarehouseModule,
  SyncModule,
  FilesModule,
} from '@dos/core'

/** Everything the distributor owner does at the desk or on the phone: masters, costs, prices, staff, approvals, registers, settings. */
export const service = defineService({
  name: 'owner',
  title: 'Owner service',
  defaultPort: 3001,
  roles: ['owner'],
  modules: [
    TenancyModule,
    CatalogModule,
    TenantCatalogModule,
    RetailersModule,
    PricingModule,
    InventoryModule,
    ProcurementModule,
    OrdersModule,
    ReceivablesModule,
    BillingModule,
    WarehouseModule,
    SyncModule,
    FilesModule,
  ],
  contractKeys: [
    'health',
    'tenancy',
    'catalog',
    'tenantCatalog',
    'retailers',
    'pricing',
    'inventory',
    'procurement',
    'orders',
    'receivables',
    'billing',
    'warehouse',
    'sync',
    'files',
  ],
})
