/**
 * Every user-visible word in the sales app, with a locale key.
 *
 * English only for the pilot (founder, 2026-09-05) — and because every word is here, Hindi and
 * Marathi are a translation file with the same keys, never a rewrite. No component in this app holds
 * an English sentence.
 *
 * The writing rules are UX-00 §12: the trade's own word, labels ≤ 20 characters, buttons are verb +
 * object, state the NEXT ACTION rather than the problem, never "Oops", never an exclamation mark,
 * never an emoji. A field app has one more rule on top: a sentence a rep reads while standing in a
 * doorway in the sun has to be true at a glance, so "Saved on this phone" and "Order placed" are
 * different sentences and are never swapped.
 *
 * `word.*` keys translate the services' own enum values (`no_order`, `POST_FULFILLMENT`,
 * `auto_approved`); anything without a key is humanised by the kit rather than printed raw.
 */
export const strings = {
  // --- the frame (docs/23 §0) ---------------------------------------------------------------
  'app.signIn': 'Sign in',
  'app.signInTitle': 'Sign in',
  'app.username': 'Username',
  'app.password': 'Password',
  'app.signInFailed': 'Could not sign in',
  'app.reload': 'Reload',
  'app.changePassword': 'Change your password',
  'app.passwordForced':
    'This password was given to you by someone else. Set your own before you carry on.',
  'app.passwordVoluntary': 'Choose a new password for this account.',
  'app.currentPassword': 'Current password',
  'app.newPassword': 'New password',
  'app.repeatPassword': 'New password again',
  'app.passwordRule': 'At least 8 characters, with a letter and a digit',
  'app.passwordMismatch': 'The two new passwords are not the same',
  'app.passwordNeedsCurrent': 'Enter the password you signed in with',
  'app.passwordRevokes': 'Your other devices will be signed out.',
  'app.setPassword': 'Set password',
  'app.passwordFailed': 'Could not change the password',
  /* What a rep needs at the door, not what a developer finds interesting about the build. */
  'app.signInHelp': 'Use the username your distributor gave you.',
  /*
   * A role sales-service does not serve (docs/22 §2: "a service serves only its roles"). Without
   * this the app signed a manager in, drew the salesperson's shell around an empty beat and left
   * "Still loading the beat onto this phone" on the screen for ever, because every call — the sync
   * manifest included — comes back 403 "sales-service does not serve the manager role".
   */
  'app.wrongRoleTitle': 'This app is for the sales team',
  'app.wrongRoleBody':
    'You are signed in as {role}. Nothing here will load. Use the app your distributor gave you for that job, or sign in with a salesperson account.',
  'app.signOut': 'Sign out',
  'app.none': '—',
  'app.rows': '{count} rows',
  'app.asOf': 'as of {when}',

  // --- X4 my account and my devices ---------------------------------------------------------
  'x4.title': 'My account',
  'x4.name': 'Name',
  'x4.role': 'Role',
  'x4.devices': 'Devices signed in',
  'x4.device': 'Device',
  'x4.platform': 'Platform',
  'x4.signedInAt': 'Signed in',
  'x4.lastSeen': 'Last used',
  'x4.thisDevice': 'This device',
  'x4.revoke': 'Sign out device',
  'x4.revokeBody': 'That device will have to sign in again with a password.',
  'x4.unnamed': 'Unnamed device',
  'x4.noDevices': 'No other device is signed in',

  // --- shared honesty lines about the phone's own copy ---------------------------------------
  's0.filling': 'Still loading the beat onto this phone',
  's0.offlineNote': 'No signal. Everything on this screen is the copy on this phone.',
  's0.offlineChip': 'No signal',
  's0.needsSignal': 'This needs a signal',
  's0.notPersisted': 'This browser will not keep the offline copy after you close it',
  's0.catalogMissing': 'The catalog has not reached this phone yet',

  // --- S1 today's beat ------------------------------------------------------------------------
  's1.title': "Today's beat",
  's1.noBeat': 'No beat today',
  's1.search': 'Search this beat',
  's1.shopsCount': 'Shops: {count}',
  's1.visitedCount': 'Visited: {count}',
  's1.orderedCount': 'Ordered: {count}',
  's1.stateOrdered': 'Ordered',
  's1.stateVisited': 'Visited',
  's1.statePending': 'To visit',
  's1.visitedAt': '{when} · {outcome}',
  /*
   * "From you", because that is all this device knows. `sales_orders` is pulled scoped to the
   * signed-in rep (docs/23 §3.4), so a shop another rep sold to three days ago carries no order
   * here — and a bare "No order yet" reads as "this shop has never bought", which is the one
   * reading that would send a rep past it.
   */
  's1.lastOrderNone': 'No order from you yet',
  's1.lastOrderAt': 'your last order {when}',
  's1.empty': 'No shops on this beat yet',
  's1.noMatch': 'Nothing matches that',

  // --- S2 shop card, and the shops list -------------------------------------------------------
  's2.title': 'Shop',
  's2.tab': 'Shops',
  's2.shopsTitle': 'Shops',
  's2.shopsCount': 'Shops: {count}',
  's2.searchShops': 'Search by name, code or phone',
  's2.noShops': 'No shops on this phone yet',
  's2.capped': 'Showing {shown} of {total}. Type a name to narrow it.',
  's2.notOnDevice': 'That shop is not on this phone',
  's2.owes': 'Owes {amount}',
  's2.limit': 'Limit {amount}',
  's2.overdue': 'Overdue {amount}',
  's2.tabOverview': 'Shop',
  's2.tabOrders': 'Orders',
  's2.tabBills': 'Bills',
  's2.takeOrder': 'Take order',
  // Device-scoped like the beat's line: `useLastOrderOf` reads the rep's own orders (docs/23 §3.4).
  's2.lastOrder': 'Your last order {when}',
  's2.noLastOrder': 'No order yet',
  's2.ageing': 'How old the dues are',
  's2.asOf': 'as of {when}',
  's2.credit': 'Credit',
  's2.creditLimit': 'Credit limit',
  's2.creditDays': 'Credit days',
  's2.openBills': 'Open bills',
  's2.terms': 'Terms',
  's2.creditRunsAtSubmit':
    'The office checks the credit ({mode}) when the order is submitted, not here.',
  's2.schemes': 'Schemes this shop is in',
  's2.schemesMeta': 'Live today. The price screen applies them.',
  's2.schemeWindow': '{from} to {to}',
  's2.habits': 'How this shop buys',
  's2.ordersLast30': 'Orders, 30 days',
  's2.valueLast30': 'Value, 30 days',
  's2.avgDaysToPay': 'Days to pay',
  's2.lapsedRisk': 'Risk of losing',
  's2.contact': 'Contact',
  's2.owner': 'Owner',
  's2.phone': 'Phone',
  's2.gstin': 'GSTIN',
  's2.tier': 'Tier',
  's2.address': 'Address',
  's2.noOrders': 'No orders for this shop yet',
  's2.checkIn': 'Record a visit',
  's2.checkInBody': 'Say what happened at the door. A no-order reason is worth more than a blank.',
  's2.visitReason': 'Reason',
  's2.visitReasonHelp': 'Why there was no order, in your own words',
  's2.recordVisit': 'Record visit',
  's2.visitRecorded': 'Visit recorded',
  's2.visitNeedsSignal': 'A visit needs a signal — it is not queued on the phone yet',
  's2.tagPosition': 'Tag my position',
  's2.locating': 'Finding you',
  's2.noPosition': 'No position',
  's2.positionTagged': 'Position tagged',
  's2.metresAway': '{metres} m from the shop',

  // --- S3 order entry -------------------------------------------------------------------------
  's3.title': 'Order',
  's3.thisOrder': 'This order',
  's3.emptyOrder': 'Nothing on this order yet',
  's3.linesCount': 'Items: {count}',
  's3.schemeTotal': 'Schemes {amount}',
  's3.schemeFooter': 'Schemes on this order −{amount}',
  's3.summary': 'Items {lines} · {qty}',
  's3.beforeGst': 'before GST',
  's3.place': 'Place order',
  's3.placed': 'Order placed',
  's3.queue': 'Save on this phone',
  's3.queued': 'Saved on this phone',
  's3.placedTitle': 'Order placed',
  's3.placedBody': 'The office has it, with its number and its price.',
  's3.queuedTitle': 'Saved on this phone',
  's3.queuedBody':
    'It goes to the office as a draft as soon as there is a signal. Submit it from My orders once it lands.',
  's3.openOrder': 'Open the order',
  's3.backToBeat': 'Back to the beat',
  's3.noLines': 'Add at least one item',
  's3.clear': 'Clear',
  's3.removeLine': 'Remove',
  's3.repeatLast': 'Repeat last order ({count})',
  's3.addItems': 'Add items',
  's3.addItemsMeta': 'On this phone: {count} items',
  's3.searchItems': 'Search by item or brand',
  's3.addOneCase': 'Add a case',
  's3.caseOf': '{pieces} pc case',
  's3.available': '{cases} cs available',
  's3.rateLine': '{rate}/pc · {caseSize} pc case',
  's3.unpriced': 'No price on this phone for: {names}',
  's3.note': 'Note',
  's3.noteLabel': 'Note for the office',
  's3.noteHelp': 'Delivery instructions, a promise you made — it travels with the order',

  // --- S4 bargain -----------------------------------------------------------------------------
  's4.title': 'Ask for a lower rate',
  's4.ask': 'Ask a rate',
  's4.listRate': 'Rate now',
  's4.yourBound': 'You may drop',
  's4.boundPct': '{pct}%',
  's4.askedRate': 'Rate you are asking for (₹ per piece)',
  's4.askedHelp': 'Below the rate now, and above zero',
  's4.askedInvalid': 'That is not below the rate now',
  's4.autoApproves': 'Inside your limit — approves at once',
  's4.needsApproval': 'Over your limit — the office decides',
  's4.outcome': 'Answer: {status}',
  's4.needsSignal': 'A rate request needs a signal',
  's4.appliesAfterSync': 'The new rate reaches the order as soon as the phone syncs.',

  // --- S5 submit, status and the needs-attention tray -----------------------------------------
  's5.title': 'Order',
  's5.tab': 'Needs you',
  's5.lines': 'Items',
  's5.linesMeta': 'Lines: {count}',
  's5.noLines': 'This order has no lines yet',
  's5.approvals': 'Waiting for the office',
  's5.approvalPending': 'Nobody has decided yet',
  's5.approvalDecided': 'Decided {when}',
  's5.details': 'Details',
  's5.placedAt': 'Written',
  's5.submittedAt': 'Submitted',
  's5.notSubmitted': 'Not yet',
  's5.expected': 'Delivery expected',
  's5.note': 'Note',
  's5.orderTotal': 'Order total',
  's5.deviceTotal': 'Price on this phone',
  's5.submit': 'Submit order',
  's5.submitted': 'Submitted',
  's5.submitNeedsSignal': 'Submitting needs a signal — the office gives the number',
  's5.waitingToLand': 'Still going to the office',
  's5.backToOrders': 'My orders',
  's5.draftExplain':
    'This is a draft. Submitting it is what gives it a number and checks the shop’s credit.',
  's5.queuedExplain':
    'Saved on this phone and waiting for a signal. Nothing has reached the office yet.',
  's5.cancel': 'Cancel this order',
  's5.cancelTitle': 'Cancel this order',
  's5.cancelBody': 'Order {order} for {shop} will be cancelled and its stock released.',
  's5.cancelReason': 'Why',
  's5.cancelConfirm': 'Cancel order',
  's5.cancelNeedsSignal': 'Cancelling needs a signal',
  's5.notOnDevice': 'That order is not on this phone',
  's5.trayTitle': 'Needs you',
  's5.trayOnline': 'Signal is good. Anything waiting goes on its own.',
  's5.trayOffline': 'No signal. Everything below stays on this phone until there is one.',
  's5.needsYou': 'The office refused these',
  's5.needsYouMeta': 'Fix what it says, then try again — or throw the write away.',
  's5.nothingRejected': 'Nothing has been refused',
  's5.waitingToSend': 'Waiting to send',
  's5.waitingMeta': 'Nothing is wrong with these; they go as soon as there is a signal.',
  's5.nothingWaiting': 'Nothing is waiting',
  's5.rejected': 'Refused',
  's5.rejectedCount': 'Refused: {count}',
  's5.waitingCount': 'Waiting: {count}',
  's5.tryAgain': 'Send again',
  's5.discard': 'Throw away',
  's5.openOrder': 'Open the order',
  's5.queuedOrder': 'Order',
  's5.queuedLine': 'Order line',
  's5.notTriedYet': 'Not tried yet',
  's5.attempts': 'Tries: {count}',

  // --- S6 my orders ---------------------------------------------------------------------------
  's6.title': 'My orders',
  's6.tab': 'Orders',
  's6.viewOpen': 'Travelling',
  's6.viewAll': 'All',
  's6.viewDraft': 'Drafts',
  's6.empty': 'No orders here',
  's6.unnumbered': 'Not numbered yet',
  's6.queued': 'Waiting to send',
  's6.waitingCount': 'Waiting: {count}',
  's6.draftCount': 'Drafts: {count}',
  's6.capped': 'Showing the newest {shown} of {total}. Search a shop for older ones.',

  // --- S7 new shop ----------------------------------------------------------------------------
  's7.title': 'New shop',
  's7.context': 'The office sets the terms',
  's7.shop': 'The shop',
  's7.name': 'Shop name',
  's7.owner': 'Owner name',
  's7.phone': 'Phone',
  's7.phoneHelp': 'Ten digits. The office links it to the shop’s own sign-in later.',
  's7.where': 'Where it is',
  's7.line1': 'Building or street',
  's7.area': 'Area',
  's7.city': 'City',
  's7.pincode': 'PIN code',
  's7.beat': 'Beat',
  's7.pinHere': 'Pin this spot',
  's7.tax': 'Tax',
  's7.taxMeta': 'A registered shop gets a tax invoice; an unregistered one a bill of supply.',
  's7.gst_unregistered': 'Not registered',
  's7.gst_regular': 'Regular',
  's7.gst_composition': 'Composition',
  's7.gstin': 'GSTIN',
  's7.gstinHelp': '15 characters, as printed on the certificate',
  's7.gstinInvalid': 'That is not a valid GSTIN',
  's7.create': 'Add shop',
  's7.needName': 'A name and a phone are needed',
  's7.needsSignal': 'A new shop needs a signal',
  's7.officeSetsTerms': 'Credit limit and tier are set by the office',
  's7.linkLater': 'The office links the shop’s own sign-in to this record later.',

  // --- S8 visits ------------------------------------------------------------------------------
  's8.title': 'My visits',
  's8.tab': 'Visits',
  's8.count': 'Visits: {count}',
  's8.productive': 'Ordered: {count}',
  's8.viewAll': 'All',
  's8.viewNoOrder': 'No order',
  's8.viewOrdered': 'Ordered',
  's8.empty': 'No visits recorded yet',
  's8.recordAtShop': 'Record a visit from the shop card, where you are standing.',

  // --- S9 my performance ----------------------------------------------------------------------
  's9.title': 'Me',
  's9.tab': 'Me',
  's9.context': '{from} to {to}',
  's9.today': 'Today',
  's9.visits': 'Visits',
  's9.orders': 'Orders',
  's9.orderValue': 'Order value',
  's9.strikeRate': 'Strike rate',
  's9.last30': 'Last 30 days',
  's9.last30Meta': '{visits} visits · {orders} orders · {value}',
  's9.sparkNote': 'Order value per day, oldest on the left.',
  's9.noDays': 'No days to draw yet',
  's9.targets': 'My targets',
  's9.targetsMeta': 'Achievement is computed by the office, not on this phone.',
  's9.noTargets': 'No target is running for you',
  's9.achieved': 'Done',
  's9.target': 'Target',
  's9.targetPeriod': '{metric} · {from} to {to}',
  's9.statements': 'My payouts',
  's9.statementsMeta': 'Computed, then approved. Never paid from this app.',
  's9.noStatements': 'No payout has been computed yet',
  's9.approved': 'Approved',
  's9.computed': 'Waiting for approval',
  's9.approvedOn': 'Approved {when}',
  's9.notApproved': 'Not approved yet',
  's9.ownScope': 'These figures are yours only.',

  // --- S10 shops I am losing --------------------------------------------------------------------
  's10.title': 'Losing',
  's10.tab': 'Losing',
  's10.count': 'At risk: {count}',
  's10.none': 'none',
  's10.explain': 'Shops on your beats that have gone quiet, worst first.',
  's10.empty': 'No shop is at risk',
  's10.risk': '{pct}% risk',
  's10.lastOrder': 'Last order {when}',
  's10.neverOrdered': 'Never ordered',
  's10.ordersLast30': 'orders in 30 days: {count}',

  // --- S11 catalog, stock and deals ---------------------------------------------------------------
  's11.title': 'Catalog',
  's11.tab': 'Catalog',
  's11.itemCount': 'Items: {count}',
  's11.dealCount': 'Deals: {count}',
  's11.viewAll': 'All',
  's11.viewDeals': 'Deals',
  's11.viewStock': 'In stock',
  's11.search': 'Search by item or brand',
  's11.empty': 'The catalog has not reached this phone yet',
  's11.deals': 'Deals to pitch',
  's11.dealsMeta': 'Live today. The order screen applies them on its own.',
  's11.dealWindow': '{from} to {to} · from {trigger}',
  's11.noDeals': 'No deal is running today',
  's11.stockNeedsSignal': 'Stock figures need a signal; the items themselves are on the phone',
  's11.mrpNote': 'The figure is the printed MRP, not what the shop pays.',

  // --- S12 the shop's bills ----------------------------------------------------------------------
  's12.noBills': 'No open bill',
  's12.due': 'Due {when} · {age} days',
  's12.ofTotal': 'of {total}',
  's12.billed': 'Billed {when}',
  's12.offline':
    'No signal: these are bill totals from this phone, not what is still open on each one.',

  // --- S13 inbox -----------------------------------------------------------------------------------
  's13.title': 'Inbox',
  's13.tab': 'Inbox',
  's13.fromShops': 'From shops',
  's13.fromShopsMeta': 'Texts and photos from the shops on your beats.',
  's13.sent': 'Sent to shops',
  's13.sentMeta': 'What the office sent on your beats.',
  's13.unhandled': 'Open: {count}',
  's13.handled': 'Handled',
  's13.open': 'Open',
  's13.markHandled': 'Mark handled',
  's13.openShop': 'Open the shop',
  's13.noInbound': 'Nothing from the shops',
  's13.noSent': 'Nothing sent yet',
  's13.photoOnly': 'Photo, no words',
  's13.photoAlt': 'Photo sent by {shop}',

  // --- AI drafts -----------------------------------------------------------------------------------
  'ai.title': 'Drafts',
  'ai.tab': 'Drafts',
  'ai.explain': 'What a shop asked for by WhatsApp or voice. Nothing is ordered until you agree.',
  'ai.viewPending': 'To confirm',
  'ai.viewConfirmed': 'Confirmed',
  'ai.viewRejected': 'Thrown away',
  'ai.empty': 'No draft is waiting',
  'ai.unknownShop': 'Shop not named',
  'ai.confidence': '{pct} sure',
  'ai.draftTitle': 'Confirm the order',
  'ai.noMatch': 'No item matched',
  'ai.lineDropped': 'This line cannot be ordered until an item is chosen',
  /* Written so it reads correctly at one as well as at five: the kit has no plural rules. */
  'ai.droppedCount': 'Left out of the order: {count}',
  'ai.confirm': 'Place the order ({count})',
  'ai.reject': 'Throw the draft away',
  'ai.rejectReason': 'Why',
  'ai.rejectNeedsReason': 'Say why before throwing it away',

  // --- the services' own words --------------------------------------------------------------------
  'word.ordered': 'Ordered',
  'word.no_order': 'No order',
  'word.closed': 'Shut',
  'word.not_found': 'Not found',
  'word.payment_only': 'Payment only',
  'word.draft': 'Draft',
  'word.submitted': 'Submitted',
  'word.confirmed': 'Confirmed',
  'word.picking': 'Being picked',
  'word.packed': 'Packed',
  'word.dispatched': 'On the van',
  'word.delivered': 'Delivered',
  'word.cancelled': 'Cancelled',
  'word.closed_order': 'Closed',
  'word.auto_approved': 'Approved at once',
  'word.approved': 'Approved',
  'word.rejected': 'Refused',
  'word.requested': 'Waiting',
  'word.expired': 'Expired',
  'word.parsed': 'Read',
  'word.needs_review': 'Needs you',
  'word.salesperson': 'Salesperson',
  'word.POST_FULFILLMENT': 'Pay after delivery',
  'word.PRE': 'Pay before',
  'word.ON': 'Pay on delivery',
  'word.stop': 'Stop at the limit',
  'word.indicate': 'Warn at the limit',
  'word.allow': 'No stop',
  'word.free_qty': 'Free goods',
  'word.line_pct': 'Line discount',
  'word.order_pct': 'Order discount',
  'word.cash_discount_pct': 'Cash discount',
  'word.net_scheme_amount': 'Off the net',
  'word.pcs': 'pieces',
  'word.case': 'cases',
  'word.inr': 'rupees',
  'word.whatsapp': 'WhatsApp',
  'word.sms': 'SMS',
  'word.push': 'Push',
  'word.in_app': 'In app',
  'word.voice': 'Voice note',
  'word.bargain': 'Rate change',
  'word.credit_limit': 'Credit limit',
  'word.min_order_value': 'Minimum order',
  'word.manual_price': 'Manual price',
} as const
