/**
 * Prints a fresh EdDSA key pair for the auth service, as two .env lines.
 *   pnpm auth:keygen >> .env      (then remove any older AUTH_JWT_* lines)
 * Every service verifies with AUTH_JWT_PUBLIC_KEY; only auth-service needs AUTH_JWT_PRIVATE_KEY.
 */
import { encodeJwk, generateAuthKeys } from '@dos/core'

const { privateJwk, publicJwk, kid } = await generateAuthKeys()
console.log(`# auth keys generated by pnpm auth:keygen (kid ${kid})`)
console.log(`AUTH_JWT_PRIVATE_KEY=${encodeJwk(privateJwk)}`)
console.log(`AUTH_JWT_PUBLIC_KEY=${encodeJwk(publicJwk)}`)
