/**
 * The owner app's own string namespace, merged over the kit catalogue by `<ThemeProvider strings>`.
 *
 * English only for the pilot (founder, 2026-09-05) — and every user-visible word has a locale key, so
 * Hindi and Marathi are a translation file rather than a rewrite. No screen in this app contains a
 * literal English sentence: if a word is on screen it is here.
 *
 * Writing rules (UX-00 §12): the trade's own word, labels <= 20 characters, buttons are verb + object,
 * state the next action rather than the problem, never "Oops", never "!" and never an emoji.
 */
export const strings = {
  // --- chrome, sign-in, account (X1–X4) -----------------------------------------------------------
  'app.signIn': 'Sign in',
  'app.signInTitle': 'Sign in',
  'app.username': 'Username',
  'app.password': 'Password',
  'app.signInFailed': 'Could not sign in',
  'app.signInHint': 'Use the username your distributorship issued.',
  'app.search': 'Search shops, bills, orders',
  'app.searchShort': 'Search',
  'app.changePassword': 'Change password',
  'app.currentPassword': 'Current password',
  'app.newPassword': 'New password',
  'app.repeatPassword': 'New password again',
  'app.passwordChanged': 'Password changed',
  'app.passwordForced':
    'This password was given to you by someone else. Set your own before you carry on.',
  'app.passwordVoluntary': 'Choose a new password for this account.',
  'app.passwordRule': 'At least 8 characters, with a letter and a digit',
  'app.passwordMismatch': 'The two new passwords are not the same',
  'app.passwordNeedsCurrent': 'Enter the password you signed in with',
  'app.passwordRevokes': 'Your other devices will be signed out.',
  'app.setPassword': 'Set password',
  'app.passwordFailed': 'Could not change the password',
  'app.devices': 'Devices & sessions',
  'app.session': 'Signed in',
  'app.revoke': 'Sign out device',
  'app.reload': 'Reload',
  'app.retry': 'Try again',
  'app.export': 'Export CSV',
  'app.exportQueued': 'Export queued',
  'app.exportReady': 'Download export',
  'app.print': 'Print',
  'app.open': 'Open',
  'app.save': 'Save changes',
  'app.saved': 'Saved',
  'app.close': 'Close',
  'app.apply': 'Apply',
  'app.filters': 'Filters',
  'app.clear': 'Clear',
  'app.more': 'Load more',
  'app.none': '—',
  'app.rows': '{count} rows',
  'app.of': '{shown} of {total}',
  'app.asOf': 'as of {when}',
  'app.range': '{from} — {to}',
  'app.from': 'From',
  'app.to': 'To',
  'app.noAccess': 'This sign-in cannot open that',
  'app.notBuilt': 'Nothing to show here yet',
  'app.nothingChanged': 'Change something first',
  'app.keyboardHint': 'Press / to search, Esc to close, Enter to commit',
  'app.drill': 'Open the rows behind this',
  'app.today': 'Today',
  'app.days7': '7 days',
  'app.days30': '30 days',
  'app.days90': '90 days',
  'app.months12': '12 months',
  'app.fy': 'This FY',

  // --- O1 Today ------------------------------------------------------------------------------------
  'o1.tab': 'Today',
  'o1.title': 'Today',
  'o1.sales': 'Invoiced today',
  'o1.collected': 'Collected today',
  'o1.outstanding': 'Outstanding',
  'o1.cashInTransit': 'Cash in transit',
  'o1.orders': 'Orders today',
  'o1.stops': 'Stops delivered',
  'o1.overdue': '{amount} overdue',
  'o1.trips': '{count} trips active',
  'o1.failedStops': '{count} failed',
  'o1.stopsDone': '{count} stops delivered',
  'o1.needsYou': 'Needs you',
  'o1.needsYouCount': 'Needs you ({count})',
  'o1.openApprovals': 'Open approvals',
  'o1.noApprovals': 'Nothing waiting for you',
  'o1.week': 'Last 7 days',
  'o1.salesLine': 'Invoiced',
  'o1.collectedLine': 'Collected',
  'o1.mtdSales': 'Sales this month',
  'o1.stockValue': 'Stock at cost',
  'o1.nearExpiry': '{amount} near expiry',
  'o1.atRisk': 'At-risk stock',
  'o1.activeTrips': 'Active trips',
  'o1.viewMap': 'Open live map',

  // --- O3 Approvals --------------------------------------------------------------------------------
  'o3.tab': 'Approvals',
  'o3.title': 'Approvals',
  'o3.kind': 'Kind',
  'o3.what': 'What',
  'o3.asked': 'Asked',
  'o3.decide': 'Decision',
  'o3.approve': 'Approve',
  'o3.reject': 'Reject',
  'o3.ask': 'Ask again',
  'o3.note': 'Note for the person who asked',
  'o3.approved': 'Approved',
  'o3.rejected': 'Rejected',
  'o3.bargains': 'Rate requests',
  'o3.orderApprovals': 'Order approvals',
  'o3.grnExceptions': 'GRN exceptions',
  'o3.listRate': 'List rate',
  'o3.askedRate': 'Asked rate',
  'o3.gap': 'Gap',
  'o3.empty': 'Nothing waiting for a decision',
  'o3.keys': 'j / k move · 1 approve · 2 reject',
  'o3.confirmApprove': 'Approve {what}',
  'o3.confirmReject': 'Reject {what}',
  'o3.decided': 'Decision recorded',

  // --- O4 Live map ---------------------------------------------------------------------------------
  'o4.tab': 'Live map',
  'o4.title': 'Vehicles now',
  'o4.vehicle': 'Vehicle',
  'o4.driver': 'Driver',
  'o4.seen': 'Last seen',
  'o4.position': 'Position',
  'o4.speed': 'Speed',
  'o4.stops': 'Stops',
  'o4.noPositions': 'No vehicle has reported a position today',
  'o4.mapNote': 'Map tiles arrive with the MapView component; positions are live.',
  'o4.openInMaps': 'Open in maps',
  'o4.trace': 'Trip trace',

  // --- O5 Orders + O18 Trips -----------------------------------------------------------------------
  'o5.tab': 'Orders',
  'o5.title': 'Orders',
  'o5.orderNo': 'Order',
  'o5.shop': 'Shop',
  'o5.state': 'State',
  'o5.value': 'Value ₹',
  'o5.placed': 'Placed',
  'o5.flags': 'Waiting on',
  'o5.confirm': 'Confirm order',
  'o5.cancel': 'Cancel order',
  'o5.cancelReason': 'Why is it cancelled',
  'o5.reservations': 'Stock held',
  'o5.release': 'Release stock',
  'o5.bills': 'Bills',
  'o5.detail': 'Order {no}',
  'o5.lines': '{count} lines',
  'o5.subtotal': 'Subtotal',
  'o5.discount': 'Discount',
  'o5.tax': 'GST',
  'o5.roundOff': 'Round off',
  'o5.total': 'Total',
  'o5.terms': 'Payment terms',
  'o5.expected': 'Expected on',
  'o5.empty': 'No orders in this window',
  'o18.tab': 'Trips',
  'o18.title': 'Trips & settlements',
  'o18.tripNo': 'Trip',
  'o18.date': 'Date',
  'o18.vehicle': 'Vehicle',
  'o18.stops': 'Stops',
  'o18.collected': 'Collected ₹',
  'o18.expenses': 'Expenses ₹',
  'o18.settle': 'Settle trip',
  'o18.preview': 'Settlement',
  'o18.expected': 'Expected',
  'o18.counted': 'Counted',
  'o18.variance': 'Variance',
  'o18.empty': 'No trips in this window',

  // --- O6 Shops -------------------------------------------------------------------------------------
  'o6.title': 'Shops',
  'o6.code': 'Code',
  'o6.name': 'Shop',
  'o6.beat': 'Beat',
  'o6.allBeats': 'All beats',
  'o6.tier': 'Tier',
  'o6.dues': 'Owes ₹',
  'o6.limit': 'Limit ₹',
  'o6.terms': 'Terms',
  'o6.trend': '12 weeks',
  'o6.detail': '{name}',
  'o6.credit': 'Credit',
  'o6.setCredit': 'Set credit',
  'o6.creditLimit': 'Credit limit',
  'o6.creditDays': 'Credit days',
  'o6.creditBills': 'Open bills allowed',
  'o6.creditMode': 'When it is crossed',
  'o6.statement': 'Send statement',
  'o6.statementSent': 'Statement sent',
  'o6.ledger': 'Ledger',
  'o6.behaviour': 'Behaviour',
  'o6.visits': 'Visits',
  'o6.overrides': 'Price overrides',
  'o6.bills': 'Bills',
  'o6.gstin': 'GSTIN',
  'o6.phone': 'Phone',
  'o6.address': 'Address',
  'o6.avgDaysToPay': 'Average days to pay',
  'o6.lastOrder': 'Last order',
  'o6.empty': 'No shop matches',

  // --- O7 Beats & staff -------------------------------------------------------------------------------
  'o7.title': 'Beats & staff',
  'o7.beats': 'Beats',
  'o7.staff': 'Staff',
  'o7.bounds': 'Discount bounds',
  'o7.brands': 'Brands a rep may sell',
  'o7.beatName': 'Beat',
  'o7.area': 'Area',
  'o7.visitDays': 'Visit days',
  'o7.assignments': 'Reps on this beat',
  'o7.person': 'Person',
  'o7.username': 'Username',
  'o7.role': 'Role',
  'o7.status': 'Status',
  'o7.lastLogin': 'Last sign-in',
  'o7.addStaff': 'Add staff',
  'o7.resetPassword': 'Set password',
  'o7.disable': 'Disable',
  'o7.enable': 'Enable',
  'o7.maxDiscount': 'Most a rep may give',
  'o7.needsApproval': 'Above this, ask the owner',

  // --- O8 Prices & schemes ------------------------------------------------------------------------------
  'o8.title': 'Prices & schemes',
  'o8.priceLists': 'Price lists',
  'o8.schemes': 'Schemes',
  'o8.overrides': 'Shop overrides',
  'o8.quote': 'What-if',
  'o8.listName': 'Price list',
  'o8.tier': 'Tier',
  'o8.default': 'Default',
  'o8.valid': 'Valid',
  'o8.items': 'Rates',
  'o8.rate': 'Rate ₹',
  'o8.item': 'Item',
  'o8.scheme': 'Scheme',
  'o8.trigger': 'Trigger',
  'o8.reward': 'Reward',
  'o8.funding': 'Funded by',
  'o8.claimable': 'Claimable',
  'o8.stackable': 'Stacks',
  'o8.final': 'Final',
  'o8.overrideRate': 'Override ₹',
  'o8.quoteRun': 'Price this basket',
  'o8.quoteShop': 'Shop',
  'o8.quoteItem': 'Item',
  'o8.quoteQty': 'Pieces',
  'o8.quoteNet': 'Net',
  'o8.quoteRules': 'Rules applied',
  'o8.empty': 'No price list yet',

  // --- O9 Catalog, costs, suppliers ------------------------------------------------------------------
  'o9.tab': 'Catalog',
  'o9.title': 'Catalog, costs & suppliers',
  'o9.listed': 'Listed items',
  'o9.costs': 'Purchase cost',
  'o9.suppliers': 'Suppliers',
  'o9.brands': 'Brands',
  'o9.packs': 'Buy-side packs',
  'o9.item': 'Item',
  'o9.brand': 'Brand',
  'o9.caseSize': 'Case size',
  'o9.mrp': 'MRP ₹',
  'o9.cost': 'Cost ₹',
  'o9.landed': 'Landed ₹',
  'o9.supplier': 'Supplier',
  'o9.gstin': 'GSTIN',
  'o9.minOrder': 'Min order',
  'o9.ownerOnly': 'Cost is visible to the back office only',
  'o9.search': 'Search the global catalog',
  'o9.listedOnly': 'Only what I sell',

  // --- O10 Outstanding & ageing -----------------------------------------------------------------------
  'o10.tab': 'Outstanding',
  'o10.title': 'Money owed',
  'o10.shop': 'Shop',
  'o10.dues': 'Outstanding ₹',
  'o10.overdue': 'Overdue ₹',
  'o10.bills': 'Open bills',
  'o10.oldest': 'Oldest due',
  'o10.mode': 'On the limit',
  'o10.buckets': 'Money owed, by age',
  'o10.byShop': 'Shop by shop',
  'o10.history': 'Ageing over time',
  'o10.rebuild': 'Rebuild ageing',
  'o10.writeOff': 'Write off',
  'o10.writeOffAmount': 'Amount to write off',
  'o10.writeOffReason': 'Reason',
  'o10.cashDiscounts': 'Cash-discount windows',
  'o10.statements': 'Send statements',
  'o10.empty': 'Nothing is owed',

  // --- O11 Receipts & banking --------------------------------------------------------------------------
  'o11.tab': 'Receipts',
  'o11.title': 'Receipts & banking',
  'o11.receiptNo': 'Receipt',
  'o11.shop': 'Shop',
  'o11.mode': 'Mode',
  'o11.amount': 'Amount ₹',
  'o11.unallocated': 'On account ₹',
  'o11.status': 'Status',
  'o11.received': 'Received',
  'o11.record': 'Record receipt',
  'o11.reverse': 'Reverse receipt',
  'o11.deposit': 'Bank it',
  'o11.bounce': 'Mark bounced',
  'o11.bounceReason': 'Why it bounced',
  'o11.allocate': 'Allocate to a bill',
  'o11.document': 'Receipt document',
  'o11.counted': 'Counted',
  'o11.onAccount': 'On account',
  'o11.empty': 'No receipts in this window',

  // --- O12 Books ------------------------------------------------------------------------------------------
  'o12.tab': 'Books',
  'o12.title': 'Trial balance & day book',
  'o12.account': 'Account',
  'o12.code': 'Code',
  'o12.kind': 'Kind',
  'o12.balance': 'Balance ₹',
  'o12.entry': 'Entry',
  'o12.date': 'Date',
  'o12.narration': 'Narration',
  'o12.debit': 'Debit ₹',
  'o12.credit': 'Credit ₹',
  'o12.dayBook': 'Day book',
  'o12.trialBalance': 'Trial balance',
  'o12.balanced': 'Debits equal credits',
  'o12.unbalanced': 'Debits and credits differ',

  // --- O13 Billing + O14 Credit notes -------------------------------------------------------------------
  'o13.tab': 'Bills',
  'o13.title': 'Bills & GST',
  'o13.invoiceNo': 'Bill',
  'o13.date': 'Date',
  'o13.shop': 'Shop',
  'o13.taxable': 'Taxable ₹',
  'o13.tax': 'GST ₹',
  'o13.total': 'Total ₹',
  'o13.due': 'Due ₹',
  'o13.state': 'State',
  'o13.pdf': 'Open bill',
  'o13.pdfQueued': 'The bill is being prepared — press again in a moment',
  'o13.printBill': 'Print bill',
  'o13.cancel': 'Cancel bill',
  'o13.eway': 'Record e-way bill',
  'o13.ewayNo': 'E-way bill number',
  'o13.irn': 'Request IRN',
  'o13.upi': 'UPI QR',
  'o13.gst': 'GST summary',
  'o13.salesRegister': 'Sales register',
  'o13.hsn': 'HSN',
  'o13.rate': 'Rate',
  'o13.empty': 'No bills in this window',
  'o14.tab': 'Credit notes',
  'o14.title': 'Credit notes',
  'o14.noteNo': 'Note',
  'o14.against': 'Against bill',
  'o14.reason': 'Reason',
  'o14.issue': 'Issue note',
  'o14.cancelNote': 'Cancel note',
  'o14.empty': 'No credit notes yet',

  // --- O15 Stock -------------------------------------------------------------------------------------------
  'o15.tab': 'Stock',
  'o15.title': 'Stock',
  'o15.item': 'Item',
  'o15.batch': 'Batch',
  'o15.location': 'Location',
  'o15.onHand': 'On hand',
  'o15.reserved': 'Held',
  'o15.sellable': 'Sellable',
  'o15.expiry': 'Expiry',
  'o15.mrp': 'MRP ₹',
  'o15.value': 'Value ₹',
  'o15.ledger': 'Stock ledger',
  'o15.balances': 'Balances',
  'o15.movement': 'Movement',
  'o15.reason': 'Reason',
  'o15.ref': 'Document',
  'o15.adjust': 'Adjust stock',
  'o15.transfer': 'Transfer stock',
  'o15.counts': 'Cycle counts',
  'o15.locations': 'Locations',
  'o15.nearExpiry': 'Near expiry',
  'o15.byBrand': 'Stock value by brand',
  'o15.empty': 'No stock at this location',

  // --- O16 Inbound + O26 Documents ---------------------------------------------------------------------------
  'o16.tab': 'Inbound',
  'o16.title': 'Supplier bills, GRNs & POs',
  'o16.supplierInvoices': 'Supplier bills',
  'o16.grns': 'Goods received',
  'o16.pos': 'Purchase orders',
  'o16.discrepancies': 'Discrepancies',
  'o16.invoiceNo': 'Bill',
  'o16.supplier': 'Supplier',
  'o16.status': 'Status',
  'o16.total': 'Total ₹',
  'o16.grnNo': 'GRN',
  'o16.poNo': 'PO',
  'o16.expected': 'Expected',
  'o16.kind': 'Kind',
  'o16.qty': 'Pieces',
  'o16.resolve': 'Resolve',
  'o16.resolution': 'How it was settled',
  'o16.empty': 'Nothing inbound yet',
  'o26.tab': 'Documents',
  'o26.title': 'Documents inbox',
  'o26.document': 'Document',
  'o26.uploaded': 'Uploaded by',
  'o26.age': 'Waiting',
  'o26.lines': 'Lines',
  'o26.red': 'Red',
  'o26.amber': 'Amber',
  'o26.qr': 'QR',
  'o26.review': 'Review document',
  'o26.quality': 'Reading quality',
  'o26.documents': 'Documents read',
  'o26.editsPerTen': 'Edits per ten lines',
  'o26.failed': 'Failed to read',
  'o26.waiting': 'Waiting in the inbox',
  'o26.empty': 'The inbox is clear',
  'o26.minutes': '{count} min',
  'o26.hours': '{count} h',
  'o26.days': '{count} d',

  // --- O2 Growth & performance ---------------------------------------------------------------------------------
  'o2.tab': 'Growth',
  'o2.title': 'Growth & performance',
  'o2.salesTrend': 'Sales, day by day',
  'o2.salesVsPrev': 'Sales vs the period before',
  'o2.monthOnMonth': 'Month by month',
  'o2.collectionsVsSales': 'Collections against sales',
  'o2.brandMix': 'Brand mix',
  'o2.byBeat': 'Sales by beat',
  'o2.byRep': 'Sales by rep',
  'o2.topShops': 'Top shops',
  'o2.outstandingTrend': 'Outstanding and overdue',
  'o2.fillRate': 'Fill rate',
  'o2.delivery': 'Delivery performance',
  'o2.stockCover': 'Stock cover',
  'o2.compare': 'Compare with',
  'o2.comparePrev': 'Previous period',
  'o2.compareYear': 'Last year',
  'o2.compareNone': 'Nothing',
  'o2.grain': 'Grain',
  'o2.day': 'Day',
  'o2.week': 'Week',
  'o2.month': 'Month',
  'o2.share': '{pct} of sales',
  'o2.shareHead': 'Share',
  'o2.rank': '#',

  // --- O17 Profit ---------------------------------------------------------------------------------------------
  'o17.tab': 'Profit',
  'o17.title': 'Profit',
  'o17.ownerOnly': 'Owner only. Nobody else can open this page.',
  'o17.mtdMargin': 'Gross margin this month',
  'o17.marginTrend': 'Gross margin by month',
  'o17.marginByBrand': 'Margin by brand',
  'o17.schemeSpend': 'Scheme spend',
  'o17.stockValue': 'Stock at cost',
  'o17.brand': 'Brand',
  'o17.margin': 'Margin ₹',
  'o17.spend': 'Spend ₹',
  'o17.fundedBy': 'Funded by',

  // --- O19 Claims ------------------------------------------------------------------------------------------------
  'o19.tab': 'Claims',
  'o19.title': 'Claims on brands',
  'o19.claimNo': 'Claim',
  'o19.supplier': 'Brand / supplier',
  'o19.kind': 'Kind',
  'o19.period': 'Period',
  'o19.claimed': 'Claimed ₹',
  'o19.settled': 'Settled ₹',
  'o19.outstanding': 'Open ₹',
  'o19.status': 'Status',
  'o19.due': 'Due',
  'o19.ageing': 'Claim ageing',
  'o19.empty': 'No claims raised yet',

  // --- O20 Incentives ---------------------------------------------------------------------------------------------
  'o20.tab': 'Incentives',
  'o20.title': 'Targets & incentives',
  'o20.person': 'Person',
  'o20.target': 'Target',
  'o20.metric': 'Metric',
  'o20.achieved': 'Achieved',
  'o20.pct': 'Achieved %',
  'o20.period': 'Period',
  'o20.statements': 'Payout statements',
  'o20.statement': 'Statement',
  'o20.computed': 'Computed ₹',
  'o20.approveStatement': 'Approve statement',
  'o20.team': 'Team',
  'o20.empty': 'No targets set',

  // --- O21 Imports ---------------------------------------------------------------------------------------------------
  'o21.tab': 'Imports',
  'o21.title': 'Imports',
  'o21.file': 'File',
  'o21.source': 'From',
  'o21.target': 'Into',
  'o21.status': 'Status',
  'o21.rows': 'Rows',
  'o21.ok': 'OK',
  'o21.errors': 'Errors',
  'o21.newImport': 'New import',
  'o21.pickFile': 'Choose a file',
  'o21.dryRun': 'Dry run',
  'o21.commit': 'Commit import',
  'o21.cancelImport': 'Cancel import',
  'o21.rollback': 'Roll back',
  'o21.profiles': 'Saved column maps',
  'o21.preview': 'Preview',
  'o21.empty': 'No import started yet',

  // --- O22 Exports & Tally ----------------------------------------------------------------------------------------------
  'o8.gstIncluded': 'Rate includes GST',
  'o17.unnamedScheme': 'Scheme {ref}',
  'o22.tab': 'Exports',
  'o22.title': 'Exports & Tally',
  'o22.kind': 'Kind',
  'o22.status': 'Status',
  'o22.requested': 'Requested',
  'o22.rowCount': 'Rows',
  'o22.download': 'Download',
  'o22.register': 'Register',
  'o22.format': 'Format',
  'o22.request': 'Request export',
  'o22.tally': 'Tally ledger map',
  'o22.tallyLedger': 'Tally ledger',
  'o22.syncLedger': 'Tally sync log',
  'o22.empty': 'No export requested yet',

  // --- O23 Notifications ------------------------------------------------------------------------------------------------
  'o23.tab': 'Messages',
  'o23.title': 'Messages & templates',
  'o23.templates': 'Templates',
  'o23.messages': 'Sent messages',
  'o23.broadcasts': 'Broadcasts',
  'o23.inbound': 'Replies',
  'o23.channel': 'Channel',
  'o23.key': 'Template',
  'o23.body': 'Body',
  'o23.destination': 'To',
  'o23.status': 'Status',
  'o23.sent': 'Sent',
  'o23.resend': 'Send again',
  'o23.markHandled': 'Mark handled',
  'o23.cost': 'Cost ₹',
  'o23.empty': 'Nothing sent yet',

  // --- O24 Settings -----------------------------------------------------------------------------------------------------
  'o24.tab': 'Settings',
  'o24.title': 'Settings',
  'o24.business': 'Business profile',
  'o24.branding': 'Branding',
  'o24.numbering': 'Numbering series',
  'o24.flags': 'Feature flags',
  'o24.policy': 'Delivery & policy',
  'o24.support': 'Support access',
  'o24.legalName': 'Legal name',
  'o24.displayName': 'Display name',
  'o24.gstin': 'GSTIN',
  'o24.stateCode': 'State code',
  'o24.fssai': 'FSSAI licence',
  'o24.address': 'Address on the bill',
  'o24.invoiceFooter': 'Bill footer',
  'o24.upi': 'UPI address',
  'o24.logo': 'Logo',
  'o24.uploadLogo': 'Upload logo',
  'o24.logoHint': 'PNG or JPG, square, at least 256 px',
  'o24.preview': 'How it prints',
  'o24.series': 'Series',
  'o24.prefix': 'Prefix',
  'o24.next': 'Next number',
  'o24.lockedHint': 'Locked once the first document is issued',
  'o24.flag': 'Flag',
  'o24.on': 'On',
  'o24.off': 'Off',
  'o24.settingKey': 'Setting',
  'o24.settingValue': 'Value',
  'o24.geofence': 'Geofence metres',
  'o24.tolerance': 'Settlement tolerance ₹',
  'o24.pod': 'Proof of delivery',
  'o24.gpsRetention': 'GPS kept for (days)',
  'o24.ewbThreshold': 'E-way bill threshold ₹',
  'o24.supportWindow': 'Support window',
  'o24.approveSupport': 'Approve access',
  'o24.revokeSupport': 'Revoke access',
  'o24.subscription': 'Subscription',
  'o24.saveSetting': 'Save setting',

  // --- O25 Audit ------------------------------------------------------------------------------------------------------------
  'o25.tab': 'Audit',
  'o25.title': 'Audit & security',
  'o25.when': 'When',
  'o25.who': 'Who',
  'o25.action': 'Action',
  'o25.entity': 'On',
  'o25.before': 'Before',
  'o25.after': 'After',
  'o25.sessions': 'Signed-in devices',
  'o25.device': 'Device',
  'o25.lastSeen': 'Last used',
  'o25.empty': 'Nothing recorded yet',

  // --- shared vocabulary ---------------------------------------------------------------------------------------------------
  'word.beat': 'Beat',
  'word.rep': 'Rep',
  'word.brand': 'Brand',
  'word.all': 'All',
  'word.active': 'Active',
  'word.pending': 'Pending',
  'word.yes': 'Yes',
  'word.no': 'No',
  'word.total': 'Total',
  'word.count': 'Count',

  /*
   * --- the services' own enum values, in the trade's words (`src/lib/words.ts`) -------------------
   *
   * `useWord()` looks a value up as `word.<value>`; a value with no key here is humanised
   * (`partly_settled` -> "Partly settled"), so this list carries only the ones where the machine word
   * and the shop's word differ, or where an initialism must stay upright (UPI, GST, POD, GRN).
   * Values shared by two enums are spelled the way BOTH read correctly.
   */

  // order + trip + stop states
  'word.partially_delivered': 'Part delivered',
  'word.settled_with_variance': 'Settled, variance',
  'word.return_undelivered': 'Returned to godown',

  // approvals
  'word.credit_limit': 'Over credit limit',
  'word.below_floor': 'Below floor price',
  'word.manual_price': 'Price changed by hand',
  'word.scheme_override': 'Scheme overridden',
  'word.trip_settlement': 'Trip cash variance',

  // invoices and credit notes
  'word.partially_paid': 'Part paid',
  'word.written_off': 'Written off',
  'word.short_delivery': 'Short delivered',
  'word.return_saleable': 'Return, saleable',
  'word.return_damaged': 'Return, damaged',
  'word.rate_difference': 'Rate difference',
  'word.scheme_settlement': 'Scheme settlement',
  'word.brand_dms_import': 'Brand DMS import',
  'word.b2b': 'B2B',
  'word.B2B': 'B2B',
  'word.b2c': 'B2C',
  'word.B2C': 'B2C',

  // money
  'word.upi': 'UPI',
  'word.bank_transfer': 'Bank transfer',
  'word.on_account': 'On account',
  'word.at_receipt_financial_cn': 'Credit note at receipt',
  'word.on_invoice': 'On the invoice',
  'word.PRE': 'Pays in advance',
  'word.ON': 'Pays on delivery',
  'word.POST_FULFILLMENT': 'Credit',
  'word.indicate': 'Warn only',
  'word.strict': 'Needs approval',
  'word.stop': 'Blocked',

  // stock and inbound
  'word.grn': 'GRN',
  'word.fefo_override': 'FEFO overridden',
  'word.needs_review': 'Needs review',
  'word.mrp': 'MRP',
  'word.ptd': 'PTD',
  'word.hsn': 'HSN',
  'word.pod': 'POD',
  'word.gps.live_map_read': 'GPS live map read',
  'word.gps.trace_read': 'GPS trace read',
  'word.gps.points_write': 'GPS points written',
  'word.credit_only': 'Credit bills only',
  'word.always': 'Every bill',
  'word.never': 'Never',

  // people
  'word.salesperson': 'Salesperson',
  'word.platform_admin': 'Distribution OS staff',
  'word.must_change_password': 'Temporary password',

  // imports and exports
  'word.tradeezee': 'TradeEzee',
  'word.fieldassist': 'FieldAssist',
  'word.tally_xml': 'Tally XML',
  'word.gstr1_json': 'GSTR-1 JSON',
  'word.sales_register_xlsx': 'Sales register (Excel)',
  'word.outstanding_xlsx': 'Outstanding (Excel)',
  'word.eway_bill_json': 'E-way bill JSON',
  'word.einvoice_json': 'E-invoice JSON',
  'word.claim_sheet': 'Claim sheet',
  'word.gstSalesRegister': 'GST sales register',
  'word.gstPurchaseRegister': 'GST purchase register',
  'word.dailySales': 'Daily sales',
  'word.repProductivity': 'Rep productivity',
  'word.schemeSpend': 'Scheme spend',
  'word.stockValue': 'Stock value',
  'word.fillRate': 'Fill rate',
  'word.deliveryPerformance': 'Delivery performance',
  'word.opening_outstanding': 'Opening outstanding',
  'word.party_master': 'Shops',
  'word.item_master': 'Items',
  'word.sales_register': 'Sales register',
  'word.brand_dms_invoices': 'Brand DMS bills',
  'word.rolled_back': 'Rolled back',

  // messages
  'word.sms': 'SMS',
  'word.in_app': 'In the app',
  'word.pod_delivered': 'Delivery proof',
  'word.payment_received': 'Payment received',
  'word.order_confirmed': 'Order confirmed',
  'word.invoice_issued': 'Bill issued',
  'word.dues_reminder': 'Dues reminder',
  'word.scheme_announcement': 'Scheme announcement',

  // schemes and visits
  'word.free_qty': 'Free goods',
  'word.no_order': 'No order',
  'word.not_found': 'Shop not found',
  'word.payment_only': 'Payment only',
} as const
