import {
  defineService,
  TenancyModule,
  CatalogModule,
  TenantCatalogModule,
  RetailersModule,
  PricingModule,
  InventoryModule,
  OrdersModule,
  ReceivablesModule,
  BillingModule,
  WarehouseModule,
  SyncModule,
  FilesModule,
  DeliveryModule,
} from '@dos/core'

/** The delivery crew app: trips, stops, proof of delivery, collections, van sales from vehicle stock, GPS breadcrumbs, the check-in cockpit. */
export const service = defineService({
  name: 'delivery',
  title: 'Delivery service',
  defaultPort: 3005,
  roles: ['delivery'],
  modules: [
    TenancyModule,
    CatalogModule,
    TenantCatalogModule,
    RetailersModule,
    PricingModule,
    InventoryModule,
    OrdersModule,
    ReceivablesModule,
    BillingModule,
    WarehouseModule,
    SyncModule,
    FilesModule,
    DeliveryModule,
  ],
  contractKeys: [
    'health',
    'tenancy',
    'catalog',
    'tenantCatalog',
    'retailers',
    'pricing',
    'inventory',
    'orders',
    'receivables',
    'billing',
    'warehouse',
    'sync',
    'files',
    'delivery',
  ],
})
