/**
 * The shopkeeper's own string namespace, merged over the kit catalogue by `<ThemeProvider strings>`.
 *
 * English only for the pilot (founder, 2026-09-05) — and every user-visible word here has a locale
 * key, so Hindi and Marathi are a translation file, never a rewrite. No screen in this app contains
 * an English literal.
 *
 * TWO THINGS THIS NAMESPACE IS CAREFUL ABOUT.
 *
 * 1. It is the DISTRIBUTOR who is speaking, not us (docs/23 §6.5). Nothing here says "Distribution
 *    OS"; where a sentence needs a name it interpolates `{name}`, which is the distributor's own
 *    display name from `tenancy.branding.get`.
 * 2. The shop is not staff. There is no "retailer", no "tenant", no "SKU", no "ATP" and no "GRN" in
 *    any sentence below: the words are the ones used across a counter — bill, dues, order, offer.
 */
export const strings = {
  // --- chrome and the frame screens (docs/23 §0) ---------------------------------------------
  'app.home': 'Home',
  'app.signIn': 'Sign in',
  'app.signInTitle': 'Sign in',
  'app.signInBody': 'Your distributor gave you this username. Ask them if you have lost it.',
  'app.username': 'Username',
  'app.password': 'Password',
  'app.signInFailed': 'Could not sign in',
  'app.signOut': 'Sign out',
  'app.changePassword': 'Change your password',
  'app.passwordForced':
    'This password was given to you by someone else. Set your own before you carry on.',
  'app.passwordVoluntary': 'Choose a new password for this account.',
  'app.currentPassword': 'Current password',
  'app.newPassword': 'New password',
  'app.repeatPassword': 'New password again',
  'app.passwordRule': 'At least 8 characters, with a letter and a digit',
  'app.passwordMismatch': 'The two new passwords are not the same',
  'app.passwordNeedsCurrent': 'Enter the password you signed in with',
  'app.passwordRevokes': 'Your other devices will be signed out.',
  'app.setPassword': 'Set password',
  'app.passwordFailed': 'Could not change the password',
  'app.wrongRoleTitle': 'This app is for shops',
  'app.wrongRoleBody': 'You are signed in as {role}. Use the app made for that work.',
  'app.reload': 'Refresh',
  'app.asOf': 'As of {when}',
  'app.none': '—',
  'app.rows': '{count} rows',
  'app.noConnection': 'No connection. This is not the current picture.',
  'app.offlineWrite': 'No connection, so this was not sent. Nothing was lost — try again.',
  'app.onlineOnly': 'This app needs a connection. Nothing is kept on this phone.',

  // --- navigation ------------------------------------------------------------------------------
  'nav.home': 'Home',
  'nav.order': 'Place order',
  'nav.orders': 'My orders',
  'nav.dues': 'Money due',
  'nav.bills': 'My bills',
  'nav.receipts': 'Receipts',
  'nav.statement': 'Statement',
  'nav.deals': 'Offers',
  'nav.returns': 'Returns',
  'nav.inbox': 'Messages',
  'nav.shop': 'My shop',
  'nav.account': 'My account',

  // --- R2 distributor cards --------------------------------------------------------------------
  'r2.title': 'Home',
  'r2.distributors': 'YOUR DISTRIBUTORS',
  'r2.openHere': 'You are looking at {name}',
  'r2.switch': 'Open {name}',
  'r2.switching': 'Opening',
  'r2.oneOnly': 'You buy from one distributor on this app.',
  'r2.duesElsewhere': 'Open a distributor to see what is owed there.',
  'r2.shop': 'Your shop',
  'r2.owes': 'You owe',
  'r2.overdue': 'Past its date',
  'r2.openBills': 'Bills still open',
  'r2.lastBill': 'Last bill',
  'r2.lastPaid': 'Last payment',
  'r2.orderAgain': 'Order again',
  'r2.orderAgainBody': 'The same items as your last order, at today’s prices.',
  'r2.newOrder': 'Start a new order',
  'r2.payNow': 'Pay now',
  'r2.recentOrders': 'YOUR LAST ORDERS',
  'r2.nextDelivery': 'ON THE WAY',
  'r2.noDelivery': 'Nothing out for delivery',
  'r2.noOrders': 'You have not ordered yet',
  'r2.noShop': 'This distributor has not linked your shop yet',
  'r2.noShopBody': 'Ask {name} to link your shop to this login.',

  // --- R7 catalog and order editor ---------------------------------------------------------------
  'r7.title': 'Place an order',
  'r7.search': 'Search the price list',
  'r7.catalog': 'PRICE LIST',
  'r7.chosen': 'IN YOUR ORDER',
  'r7.empty': 'Nothing in this order yet',
  'r7.noItems': 'This distributor has listed nothing yet',
  'r7.noMatch': 'Nothing matches "{query}"',
  'r7.perPiece': '{rate} per piece + GST',
  'r7.yourRate': 'your rate, list {list}',
  'r7.ratesFailed': 'Prices could not be loaded just now. Pull down to try again.',
  'r7.noGstRate':
    'These prices cannot be shown yet: {name} has not set the GST rate for HSN {codes}. Ask them to set it, then open this screen again.',
  'r7.case': '{size} pc case',
  'r7.mrp': 'MRP {amount}',
  'r7.outOfStock': 'Out of stock',
  'r7.lowStock': 'Only {pieces} pc left',
  'r7.inStock': 'In stock',
  'r7.stockUnknown': 'Stock not known',
  'r7.total': 'Order total',
  'r7.gross': 'Before offers',
  'r7.discount': 'Offers',
  'r7.net': 'You pay',
  'r7.beforeGst': 'Before GST',
  'r7.gst': 'GST',
  'r7.roundOff': 'Rounding',
  'r7.cashDiscount': 'Pay within {days} days and {amount} comes off',
  'r7.cashDiscountNoWindow': 'Paying early takes {amount} off',
  'r7.free': '{pieces} pc free',
  'r7.unpriced': 'No price is set for this item. Ask {name} before ordering it.',
  'r7.priceError': 'These prices could not be worked out. The order was not sent.',
  'r7.pricing': 'Working out your price',
  'r7.place': 'Place order',
  'r7.placing': 'Sending your order',
  'r7.placed': 'Order placed',
  'r7.placedBody': 'Order {no} has gone to {name}. You will see it under My orders.',
  'r7.failed': 'The order was not sent',
  'r7.note': 'Anything to tell them',
  'r7.deliveryDate': 'When do you want it',
  'r7.askBetter': 'Ask for a better rate',
  'r7.askBetterOn': 'Ask for a better rate on {item}',
  'r7.askRate': 'The rate you want, per piece, before GST',
  'r7.askListRate': 'Today’s rate is {rate} + GST',
  'r7.askSend': 'Send the request',
  'r7.askSent': 'Asked. You will see the answer under Offers.',
  'r7.repeatFailed': 'Could not build a repeat of your last order',
  'r7.repeatEmpty': 'You have no earlier order to repeat',
  'r7.lines': '{count} items',
  'r7.linesOne': '1 item',
  'r7.clear': 'Empty this order',

  // --- R8 orders ---------------------------------------------------------------------------------
  'r8.title': 'My orders',
  'r8.all': 'All',
  'r8.open': 'Still coming',
  'r8.done': 'Delivered',
  'r8.none': 'No orders yet',
  'r8.orderNo': 'Order {no}',
  'r8.draft': 'Not sent yet',
  'r8.placedOn': 'Placed {date}',
  'r8.startedOn': 'Started {date}',
  'r8.repeatNote': 'A repeat of an earlier order',
  'r8.placedToast': 'Order {no} is with {name}.',
  'r8.itemsCount': '{count} items',
  'r8.itemsCountOne': '1 item',
  'r8.detailTitle': 'Order {no}',
  'r8.lines': 'WHAT YOU ORDERED',
  'r8.itemUnknown': 'Item no longer on this price list',
  'r8.progress': 'WHERE IT IS',
  'r8.delivery': 'DELIVERY',
  'r8.noDelivery': 'Not on a vehicle yet',
  'r8.eta': 'Expected {when}',
  'r8.stopState': 'The van is {state}',
  'r8.stopSeq': 'Stop {seq} on that round',
  'r8.bill': 'Bill {no}',
  'r8.cancel': 'Cancel this order',
  'r8.cancelReason': 'Why are you cancelling',
  'r8.cancelConfirm': 'Cancel order {no}?',
  'r8.cancelBody': 'The items are released and nothing is billed.',
  'r8.cancelled': 'Order cancelled',
  'r8.cancelFailed': 'Could not cancel the order',
  'r8.submit': 'Send this order',
  'r8.notes': 'Your note',
  'r8.lineGst': '+ GST {amount}',

  // --- R3 dues ------------------------------------------------------------------------------------
  'r3.title': 'Money you owe',
  'r3.summary': 'THE TOTAL',
  'r3.outstanding': 'You owe',
  'r3.overdue': 'Past its date',
  'r3.credit': 'Money with them',
  'r3.oldest': 'Oldest bill due',
  'r3.bills': 'BILL BY BILL, OLDEST FIRST',
  'r3.noBills': 'Nothing is pending. You are clear.',
  'r3.due': 'Due {date}',
  'r3.overdueBy': '{days} days late',
  'r3.dueIn': 'Due in {days} days',
  'r3.dueToday': 'Due today',
  'r3.openOf': '{open} left of {total}',
  'r3.cashDiscount': 'Pay by {date} and save {amount}',
  'r3.payAll': 'Pay everything',
  'r3.payBill': 'Pay this bill',
  'r3.qr': 'SCAN TO PAY',
  'r3.qrBody': 'Scan this in any UPI app. The money reaches {name}.',
  'r3.qrNone': '{name} has not set up UPI yet. Pay them the way you usually do.',

  // --- R5 pay online --------------------------------------------------------------------------------
  'r5.title': 'Pay',
  'r5.amount': 'How much are you paying',
  'r5.amountHelper': 'Leave it as it is to pay everything you owe',
  'r5.choose': 'WHICH BILLS',
  'r5.chooseBody': 'Choose nothing and it goes against your oldest bills first.',
  'r5.start': 'Start the payment',
  'r5.starting': 'Getting the UPI details',
  'r5.ref': 'Quote this reference: {ref}',
  'r5.expires': 'Good until {when}',
  'r5.payee': 'Paying {name}',
  'r5.openUpi': 'Open a UPI app',
  'r5.noUpiApp':
    'No UPI app opened on this phone. Pay {vpa} from any UPI app and quote the reference below.',
  'r5.failed': 'Could not start the payment',
  'r5.covers': 'This covers {count} bills',
  'r5.noVpa': '{name} has not set up online payment yet.',
  'r5.pending': 'The money shows here once {name} has matched it. Keep the reference.',
  'r5.overDues': 'More than you owe today. The extra stays on your account with them.',

  // --- R4 bill detail -------------------------------------------------------------------------------
  'r4.title': 'My bills',
  'r4.all': 'All',
  'r4.openOnly': 'Still to pay',
  'r4.search': 'Search a bill number',
  'r4.none': 'No bills yet',
  'r4.detailTitle': 'Bill {no}',
  'r4.from': 'FROM',
  'r4.lines': 'WHAT IS ON THIS BILL',
  'r4.taxes': 'THE TOTAL',
  'r4.taxable': 'Goods',
  'r4.cgst': 'CGST',
  'r4.sgst': 'SGST',
  'r4.igst': 'IGST',
  'r4.cess': 'Cess',
  'r4.roundOff': 'Rounding',
  'r4.total': 'Bill total',
  'r4.due': 'Still to pay',
  'r4.paid': 'Paid in full',
  'r4.credits': 'RETURNS AGAINST THIS BILL',
  'r4.noCredits': 'Nothing was returned',
  'r4.receipts': 'WHAT YOU HAVE PAID',
  'r4.noReceipts': 'No payment recorded yet',
  'r4.paidOnThisBill': 'Paid against this bill',
  'r4.stillOnThisBill': 'Still to pay on this bill',
  'r4.receiptsElsewhere':
    'Every receipt {name} has given you, with the bills it went against, is on the Receipts screen.',
  'r4.seeReceipts': 'See your receipts',
  'r4.pod': 'PROOF OF DELIVERY',
  'r4.noPod': 'No delivery record yet',
  'r4.podPhoto': 'Photograph taken at your shop',
  'r4.podSigned': 'Signed for by {name}',
  'r4.deliveredOn': 'Delivered {when}',
  'r4.deliveredLabel': 'Delivery',
  'r4.openPdf': 'Open the bill',
  'r4.printPdf': 'Print',
  'r4.pdfPending': '{name} is still making the PDF of this bill. Try again in a minute.',
  'r4.rate': '{rate} per piece',
  'r4.freeOn': '{pieces} pc free',

  // --- R6 statement ---------------------------------------------------------------------------------
  'r6.title': 'Your statement',
  'r6.opening': 'Opening balance',
  'r6.closing': 'Closing balance',
  'r6.rows': 'EVERY ENTRY',
  'r6.none': 'Nothing in this period',
  'r6.date': 'Date',
  'r6.what': 'What',
  'r6.ref': 'Number',
  'r6.debit': 'Added',
  'r6.credit': 'Taken off',
  'r6.balance': 'Balance',
  'r6.d30': 'Last 30 days',
  'r6.d90': 'Last 90 days',
  'r6.fy': 'This year',
  'r6.explain': 'A plus balance is money you still owe. A minus one is money with them.',
  'r6.partial': 'This period has more entries than one statement can show. Pick a shorter period.',

  // --- R13 receipts -----------------------------------------------------------------------------------
  'r13.title': 'Money you have paid',
  'r13.none': 'No payments recorded yet',
  'r13.no': 'Receipt {no}',
  'r13.mode': 'Paid by {mode}',
  'r13.on': 'On {when}',
  'r13.allocated': 'Set against bills',
  'r13.unallocated': 'Not set against a bill yet',
  'r13.cashDiscount': 'Early-payment discount',
  'r13.open': 'Open the receipt',
  'r13.pending': '{name} is still making the receipt. Try again in a minute.',
  'r13.total': 'Paid in this list',

  // --- R9 offers and R10 rate requests -------------------------------------------------------------------
  'r9.title': 'Offers for your shop',
  'r9.running': 'RUNNING NOW',
  'r9.none': 'No offers are running today',
  'r9.until': 'Until {date}',
  'r9.brand': 'On {brand}',
  'r9.allItems': 'On everything',
  'r9.someItems': 'On selected items',
  'r9.freeQty': 'Buy {min} {unit} and get {reward} free',
  'r9.freeItem': 'Buy {min} {unit} and get {reward} pc free of another item',
  'r9.freeItemNamed': 'Buy {min} {unit} and get {reward} pc of {item} free',
  'r9.linePctAny': 'Take {pct} off these items, on any quantity',
  'r9.orderPctAny': 'Take {pct} off any order',
  'r9.cashPct': 'Spend {min} on an order and {pct} comes off if you pay inside the discount window',
  'r9.cashPctAny': 'Pay inside the discount window and {pct} comes off the bill',
  'r9.forItem': 'On {item}',
  'r9.linePct': 'Buy {min} {unit} and take {pct} off those items',
  'r9.lineAmount': 'Buy {min} {unit} and take {amount} off',
  'r9.orderPct': 'Spend {min} on an order and take {pct} off it',
  'r9.orderAmount': 'Spend {min} on an order and take {amount} off',
  'r9.slabs': 'More you buy, more you save: {slabs}',
  'r9.slab': '{min}+ → {value}',
  'r9.unitCase': 'cases',
  'r9.unitPcs': 'pieces',
  'r9.unitAmount': 'worth',
  'r9.finalNote': 'This one is on its own — no other offer stacks with it.',
  'r9.requests': 'RATES YOU ASKED FOR',
  'r9.noRequests': 'You have not asked for a special rate',
  'r9.asked': 'You asked {rate}',
  'r9.gotRate': 'They agreed {rate}',
  'r9.waiting': 'Waiting for an answer',
  'r9.rejected': 'Not agreed',
  'r9.expires': 'Good until {when}',
  'r9.expired': 'That rate has run out',

  // --- returns ------------------------------------------------------------------------------------------
  'rt.title': 'Returns and credits',
  'rt.notes': 'CREDIT NOTES IN YOUR NAME',
  'rt.none': 'Nothing has been returned',
  'rt.no': 'Credit note {no}',
  'rt.against': 'Against bill {no}',
  'rt.reason': 'Reason: {reason}',
  'rt.howTo': 'To return goods',
  'rt.howToBody':
    'Tell the delivery crew at the door, or message {name}. They raise the credit note and it appears here.',

  // --- R12 messages ---------------------------------------------------------------------------------------
  'r12.title': 'Messages from {name}',
  'r12.titleShort': 'Messages',
  'r12.none': 'No messages yet',
  'r12.unread': '{count} not read',
  'r12.markRead': 'Mark as read',
  'r12.markedRead': 'Marked as read',
  'r12.channel': 'Sent by {channel}',
  'r12.onlyPush': 'Only messages sent inside the app can be marked read.',

  // --- R11 shop profile -------------------------------------------------------------------------------------
  'r11.title': 'My shop',
  'r11.details': 'WHAT THEY HAVE ON FILE',
  'r11.name': 'Shop name',
  'r11.nameLocked': 'Only {name} can change the shop name.',
  'r11.owner': 'Owner’s name',
  'r11.phone': 'Phone',
  'r11.altPhone': 'Another phone',
  'r11.address1': 'Address',
  'r11.area': 'Area',
  'r11.city': 'City',
  'r11.pincode': 'PIN code',
  'r11.landmark': 'Landmark',
  'r11.gstin': 'GSTIN',
  'r11.gstType': 'GST registration',
  'r11.gstRegular': 'Regular',
  'r11.gstComposition': 'Composition',
  'r11.gstUnregistered': 'Not registered',
  'r11.save': 'Save my details',
  'r11.saved': 'Saved',
  'r11.saveFailed': 'Could not save your details',
  'r11.gstinInvalid': 'That is not a valid 15-character GSTIN',
  'r11.terms': 'Payment terms',
  'r11.termsBody':
    'Your terms, tier and credit limit are set by {name} and cannot be changed here.',

  // --- X4 account -------------------------------------------------------------------------------------------
  'x4.title': 'My account',
  'x4.name': 'Name',
  'x4.role': 'You are signed in as',
  'x4.devices': 'PHONES AND BROWSERS SIGNED IN',
  'x4.device': 'Device',
  'x4.platform': 'Kind',
  'x4.signedInAt': 'Signed in',
  'x4.lastSeen': 'Last used',
  'x4.thisDevice': 'This one',
  'x4.unnamed': 'Unnamed device',
  'x4.noDevices': 'No other device is signed in',
  'x4.revoke': 'Sign this device out',
  'x4.revokeBody': 'That device has to sign in again. This one is not touched.',
  'x4.seenLine': '{platform} · signed in {signedIn} · last used {lastSeen}',
  'x4.deviceCount': '{count} signed in',

  // --- words for machine values (wordFor falls back to a humanised form) --------------------------------
  'word.draft': 'Not sent',
  'word.submitted': 'With the distributor',
  'word.approval_pending': 'Waiting for approval',
  'word.confirmed': 'Accepted',
  'word.picking': 'Being packed',
  'word.packed': 'Packed',
  'word.dispatched': 'On the way',
  'word.delivered': 'Delivered',
  'word.closed': 'Closed',
  'word.cancelled': 'Cancelled',
  'word.issued': 'To pay',
  'word.partially_paid': 'Part paid',
  'word.paid': 'Paid',
  'word.written_off': 'Written off',
  'word.pending': 'Not started',
  'word.started': 'On the way to you',
  'word.arrived': 'At your shop',
  'word.completed': 'Done',
  'word.failed': 'Could not be done',
  'word.skipped': 'Skipped',
  'word.POST_FULFILLMENT': 'Pay after delivery',
  'word.PRE': 'Pay before delivery',
  'word.ON': 'Pay on delivery',
  'word.cash': 'cash',
  'word.upi': 'UPI',
  'word.cheque': 'cheque',
  'word.neft': 'bank transfer',
  'word.rtgs': 'bank transfer',
  'word.adjustment': 'adjustment',
  'word.collected': 'Received',
  'word.deposited': 'Banked',
  'word.bounced': 'Bounced',
  'word.reversed': 'Reversed',
  'word.auto_approved': 'Agreed',
  'word.approved': 'Agreed',
  'word.rejected': 'Not agreed',
  'word.requested': 'Waiting',
  'word.expired': 'Run out',
  'word.short_delivery': 'Short delivery',
  'word.rate_difference': 'Rate difference',
  'word.damage': 'Damaged goods',
  'word.expiry': 'Expired goods',
  'word.return': 'Goods returned',
  'word.scheme': 'Offer',
  'word.other': 'Other',
  'word.retailer_app': 'You placed it',
  'word.salesperson': 'Their salesperson',
  'word.phone': 'Over the phone',
  'word.whatsapp': 'WhatsApp',
  'word.sms': 'SMS',
  'word.in_app': 'the app',
  'word.push': 'the app',
  'word.email': 'email',
  'word.van_sale': 'Bought off the van',
  'word.invoice': 'Bill',
  'word.receipt': 'Payment',
  'word.credit_note': 'Credit note',
  'word.opening': 'Opening',
  'word.write_off': 'Written off',
} as const
