/**
 * The manager + accountant app's own string namespace, merged over the kit catalogue by
 * `<ThemeProvider strings>`.
 *
 * English only for the pilot (founder, 2026-09-05) — and every user-visible word has a locale key, so
 * Hindi and Marathi are a translation file rather than a rewrite. No screen in this app contains a
 * literal English sentence: if a word is on screen it is here.
 *
 * Writing rules (UX-00 §12): the trade's own word, labels <= 20 characters, buttons are verb + object,
 * state the next action rather than the problem, never "Oops", never "!" and never an emoji.
 */
export const strings = {
  // --- chrome, sign-in, account (X1–X4) -----------------------------------------------------------
  'app.signIn': 'Sign in',
  'app.signInTitle': 'Sign in',
  'app.username': 'Username',
  'app.password': 'Password',
  'app.signInFailed': 'Could not sign in',
  'app.signInHint': 'Use the username your distributorship issued.',
  'app.search': 'Search shops, bills, orders',
  'app.searchShops': 'Shop',
  'app.searchBills': 'Bill',
  'app.searchOrders': 'Order',
  'app.filterShops': 'Filter these shops',
  'app.searchFilter': 'Any date, matching "{query}"',
  'app.searchShort': 'Search',
  'app.changePassword': 'Change password',
  'app.currentPassword': 'Current password',
  'app.newPassword': 'New password',
  'app.repeatPassword': 'New password again',
  'app.passwordChanged': 'Password changed',
  'app.passwordForced':
    'This password was given to you by someone else. Set your own before you carry on.',
  'app.passwordVoluntary': 'Choose a new password for this account.',
  'app.passwordRule': 'At least 8 characters, with a letter and a digit',
  'app.passwordMismatch': 'The two new passwords are not the same',
  'app.passwordNeedsCurrent': 'Enter the password you signed in with',
  'app.passwordRevokes': 'Your other devices will be signed out.',
  'app.setPassword': 'Set password',
  'app.passwordFailed': 'Could not change the password',
  'app.reload': 'Reload',
  'app.retry': 'Try again',
  'app.export': 'Export CSV',
  'app.exportQueued': 'Export queued',
  'app.exportReady': 'Download export',
  'app.print': 'Print',
  'app.open': 'Open',
  'app.save': 'Save changes',
  'app.saved': 'Saved',
  'app.close': 'Close',
  'app.apply': 'Apply',
  'app.filters': 'Filters',
  'app.clear': 'Clear',
  'app.more': 'Load more',
  'app.none': '—',
  'app.rows': '{count} rows',
  'app.of': '{shown} of {total}',
  'app.asOf': 'as of {when}',
  'app.range': '{from} — {to}',
  'app.from': 'From',
  'app.to': 'To',
  'app.noAccess': 'This sign-in cannot open that',
  'app.notBuilt': 'Nothing to show here yet',
  'app.nothingChanged': 'Change something first',
  'app.keyboardHint': 'Press / to search, Esc to close, Enter to commit',
  'app.drill': 'Open the rows behind this',
  'app.today': 'Today',
  'app.days7': '7 days',
  'app.days30': '30 days',
  'app.days90': '90 days',
  'app.months12': '12 months',
  'app.fy': 'This FY',
  'app.note': 'Note',
  'app.reason': 'Reason',
  'app.selectRow': 'Pick a row to see it here',
  'app.accountantRead': 'The money desk reads this register; the manager makes the changes.',

  // --- X4 Profile & devices -------------------------------------------------------------------------
  'x4.title': 'My account',
  'x4.you': 'Signed in as',
  'x4.name': 'Name',
  'x4.role': 'Role',
  'x4.devices': 'Devices signed in',
  'x4.device': 'Device',
  'x4.platform': 'Platform',
  'x4.signedInAt': 'Signed in',
  'x4.lastSeen': 'Last used',
  'x4.thisDevice': 'This device',
  'x4.revoke': 'Sign out device',
  'x4.revokeBody': 'That device will have to sign in again with a password.',
  'x4.unnamed': 'Unnamed device',
  'x4.noDevices': 'No other device is signed in',

  // --- M1 Today -----------------------------------------------------------------------------------
  'm1.title': 'Today',
  'm1.submitted': 'Orders to confirm',
  'm1.billingBacklog': 'Bills to issue',
  'm1.grnQueue': 'Goods to receive',
  'm1.documents': 'Bills to review',
  'm1.cashToBank': 'Cash to bank',
  'm1.chequesDue': 'Cheques in hand',
  'm1.collectedToday': 'Collected today',
  'm1.invoicedToday': 'Invoiced today',
  'm1.outstanding': 'Money owed',
  'm1.overdue': '{amount} overdue',
  'm1.trips': '{count} trips active',
  'm1.queues': 'What is waiting',
  'm1.openQueue': 'Open the queue',
  'm1.collectionsToday': 'Collections by mode',
  'm1.cashWindows': 'Cash-discount windows closing',
  'm1.window': 'Pay by {date}',
  'm1.noWindows': 'No discount window is open',
  'm1.nothingWaiting': 'Nothing is waiting',
  'm1.rowsMore': 'more than {count} rows',
  'm1.billsWaiting': '{count} bills to issue',
  'm1.oldest': 'Oldest {when}',
  'm1.ageing': 'Money owed, by age',

  // --- M2 Order queue -----------------------------------------------------------------------------
  'm2.tab': 'Order queue',
  'm2.title': 'Order queue',
  'm2.orderNo': 'Order',
  'm2.shop': 'Shop',
  'm2.beat': 'Beat',
  'm2.lines': 'Lines',
  'm2.value': 'Amount ₹',
  'm2.credit': 'Credit',
  'm2.state': 'State',
  'm2.placed': 'Placed',
  'm2.flags': 'Waiting on',
  'm2.confirm': 'Confirm order',
  'm2.cancel': 'Cancel order',
  'm2.release': 'Free the held stock',
  'm2.cancelReason': 'Why is it cancelled? The shop and the rep will read this.',
  'm2.detail': 'Order {no}',
  'm2.creditClear': 'Clear',
  'm2.creditLine': 'Owes {owed} · limit {limit}',
  'm2.creditOver': 'This order takes it {over} over the limit',
  'm2.creditBlocked': 'Credit is blocked for this shop',
  'm2.creditUnknown': 'Credit not checked',
  'm2.empty': 'No order is waiting',
  'm2.keys': 'j / k move · Enter open · 1 confirm · 2 cancel',
  'm2.keysRead': 'j / k move · Enter open',
  'm2.approvals': 'Waiting for a decision',
  'm2.bargains': 'Rate requests',
  'm2.approve': 'Approve',
  'm2.reject': 'Reject',
  'm2.decisionNote': 'Note for the person who asked',
  'm2.rejectNeedsNote': 'Write a note first — the person who asked will read it.',
  'm2.confirmBody': 'Stock is reserved when this is confirmed. There is no undo.',
  'm2.subtotal': 'Subtotal',
  'm2.discount': 'Discount',
  'm2.tax': 'GST',
  'm2.total': 'Total',
  'm2.terms': 'Terms',
  'm2.expected': 'Wanted by',
  'm2.askedRate': 'Asked rate',
  'm2.listRate': 'List rate',
  'm2.reservations': 'Held for this order',
  'm2.onlySubmitted': 'Only a submitted order can be confirmed',
  'm2.decideFirst':
    'Waiting on {what}. Approve or reject each one first; the last approval confirms the order.',
  'm2.nothingHeld': 'Nothing is held for this order',
  'm2.alreadyClosed': 'This order is already cancelled or delivered',
  'm2.schemeApplied': 'Scheme applied',

  // --- AI drafts ----------------------------------------------------------------------------------
  'ai.tab': 'Drafts',
  'ai.title': 'Drafts to confirm',
  'ai.source': 'Came in by',
  'ai.shop': 'Shop',
  'ai.preview': 'What they wrote',
  'ai.lines': 'Lines',
  'ai.matched': 'Matched',
  'ai.confidence': 'Confidence',
  'ai.status': 'State',
  'ai.when': 'When',
  'ai.confirm': 'Confirm order',
  'ai.reject': 'Throw it away',
  'ai.rejectReason': 'Why is it being thrown away?',
  'ai.detail': 'Draft from {shop}',
  'ai.transcript': 'What we heard',
  'ai.unmatched': '{count} lines we could not match',
  'ai.empty': 'No draft is waiting',
  'ai.confirmBody': 'This creates a normal order and submits it, priced today.',
  'ai.needsHuman': 'A person must confirm this',
  'ai.line': 'Line',
  'ai.qty': 'Quantity',
  'ai.variant': 'Item',

  // --- M4 Inbound: supplier bills, GRNs, findings, purchase orders ---------------------------------
  'm4.tab': 'Supplier bills',
  'm4.title': 'Inbound',
  'm4.bills': 'Bills',
  'm4.receipts': 'Goods received',
  'm4.findings': 'Findings',
  'm4.orders': 'Purchase orders',
  'm4.supplier': 'Supplier',
  'm4.invoiceNo': 'Bill no.',
  'm4.invoiceDate': 'Bill date',
  'm4.status': 'State',
  'm4.value': 'Amount ₹',
  'm4.linesCount': 'Lines',
  'm4.openGrn': 'Open a goods receipt',
  'm4.postGrn': 'Post the receipt',
  'm4.dispute': 'Mark it disputed',
  'm4.disputeReason': 'What is wrong with this bill?',
  'm4.cancelBill': 'Cancel the bill',
  'm4.grnNo': 'Receipt no.',
  'm4.location': 'Godown',
  'm4.counted': 'Counted',
  'm4.posted': 'Posted',
  'm4.kind': 'Finding',
  'm4.qty': 'Pieces',
  'm4.resolve': 'Decide this finding',
  'm4.resolveAccepted': 'Accept it',
  'm4.resolveClaimed': 'Claim it from the brand',
  'm4.resolveCredited': 'Supplier credited us',
  'm4.resolveWrittenOff': 'Write it off',
  'm4.resolveNote': 'What was agreed with the supplier?',
  'm4.poNo': 'Order no.',
  'm4.expectedOn': 'Expected',
  'm4.empty': 'Nothing inbound',
  'm4.detail': 'Bill {no}',
  'm4.postBody':
    'Posting writes the lots, the stock ledger and the purchase cost. There is no undo.',
  'm4.grnLines': 'Lines on this receipt',
  'm4.expectedPcs': 'Expected',
  'm4.receivedPcs': 'Received',
  'm4.damagedPcs': 'Damaged',
  'm4.matchLine': 'Match it to an item',
  'm4.onlyApproved': 'Only an approved bill can be received',
  'm4.alreadyReceived': 'This bill is already received or cancelled',
  'm4.notCounted': 'The gate has not counted this receipt yet',

  // --- M3 Documents (capture and review) -----------------------------------------------------------
  'm3.tab': 'Documents',
  'm3.title': 'Documents to review',
  'm3.supplier': 'Supplier',
  'm3.invoiceNo': 'Bill no.',
  'm3.invoiceDate': 'Bill date',
  'm3.value': 'Amount ₹',
  'm3.lines': 'Lines',
  'm3.red': 'Must fix',
  'm3.amber': 'Check',
  'm3.unmatched': 'Unmatched',
  'm3.age': 'Waiting',
  'm3.ageHours': '{count} h',
  'm3.ageMinutes': '{count} min',
  'm3.lockedBy': 'Being reviewed by {name}',
  'm3.lockedHead': 'Locked by',
  'm3.qr': 'QR',
  'm3.irnVerified': 'IRN verified',
  'm3.startReview': 'Start reviewing',
  'm3.releaseReview': 'Give it up',
  'm3.submitReview': 'This reading is right',
  'm3.approve': 'Book it as a supplier bill',
  'm3.reject': 'Reject the document',
  'm3.rejectReason': 'Why is it being rejected?',
  'm3.rerunExtract': 'Read it again',
  'm3.rematch': 'Match the items again',
  'm3.detail': '{supplier} · {no}',
  'm3.pages': 'Pages',
  'm3.checks': 'Checks',
  'm3.reading': 'What we read',
  'm3.noLines': 'The reading has no lines to book',
  'm3.candidates': 'What we think each line is',
  'm3.printed': 'On the bill',
  'm3.ourItem': 'Our item',
  'm3.score': 'Match',
  'm3.accept': 'Use this item',
  'm3.empty': 'No document is waiting',
  'm3.capture': 'Photograph a bill',
  'm3.captureHint':
    'Use the phone: photograph every page of the supplier bill, then submit it for reading.',
  'm3.approveBody': 'This books a DRAFT supplier bill. Goods are received separately, at the gate.',
  'm3.quality': 'How the reading is going',
  'm3.edits': '{count} edits per ten lines',
  'm3.checkMismatch': '{ours} here, {theirs} on the document',
  'm3.latency': 'Time to read (p95)',
  'm3.documents': 'Documents',

  // --- M19 Gate count (phone) ----------------------------------------------------------------------
  'm19.tab': 'Gate count',
  'm19.title': 'Gate count',
  'm19.hint':
    'Count what actually came off the lorry. The expected figure is hidden until you have counted.',
  'm19.pick': 'Which receipt are you counting?',
  'm19.againstBill': 'Against bill {no}',
  'm19.unnumbered': 'Not numbered yet',
  'm19.item': 'Item',
  'm19.received': 'Pieces received',
  'm19.damaged': 'Pieces damaged',
  'm19.save': 'Record the count',
  'm19.saved': 'Count recorded',
  'm19.empty': 'No goods receipt is open',
  'm19.expectedAfter': 'Expected {count} pc',
  'm19.countedLines': '{done} of {total} lines counted',

  // --- M5 Fulfilment: waves ------------------------------------------------------------------------
  'm5.tab': 'Waves',
  'm5.title': 'Fulfilment',
  'm5.queue': 'Waiting to be picked',
  'm5.picklists': 'Picking sheets',
  'm5.orderNo': 'Order',
  'm5.shop': 'Shop',
  'm5.beat': 'Beat',
  'm5.pieces': 'Pieces',
  'm5.linesCount': 'Lines',
  'm5.confirmedAt': 'Confirmed',
  'm5.createWave': 'Make a picking sheet',
  'm5.onSheet': 'On the sheet',
  'm5.selected': '{count} orders · {pieces} pc',
  'm5.pickNo': 'Sheet no.',
  'm5.status': 'State',
  'm5.orders': 'Orders',
  'm5.requested': 'Asked',
  'm5.picked': 'Picked',
  'm5.assigned': 'Picker',
  'm5.startPick': 'Start picking',
  'm5.cancelWave': 'Cancel the sheet',
  'm5.cancelBody': 'The orders on it go back to the queue.',
  'm5.empty': 'Nothing is waiting to be picked',
  'm5.noWaves': 'No picking sheet yet',
  'm5.waveBody': 'The picker gets one sheet, in FEFO order, for every order you tick.',
  'm5.pickDate': 'Pick date',
  'm5.detail': 'Sheet {no}',
  'm5.consolidated': 'By item',
  'm5.short': 'Short',
  'm5.onlyOpen': 'Only a sheet that has not started can be started or cancelled',

  // --- M20 Pick and pack (phone) -------------------------------------------------------------------
  'm20.tab': 'Pick & pack',
  'm20.title': 'Pick & pack',
  'm20.sheet': 'Picking sheet',
  'm20.item': 'Item',
  'm20.lot': 'Batch',
  'm20.askedPcs': 'Asked',
  'm20.pickedPcs': 'Picked',
  'm20.recordPick': 'Record what was picked',
  'm20.packOrder': 'Pack and bill',
  'm20.packages': 'Packages',
  'm20.weight': 'Weight (g)',
  'm20.issueInvoice': 'Issue the bill now',
  'm20.packBody':
    'Stock leaves the godown, the order moves to packed and the bill is issued. There is no undo.',
  'm20.packed': 'Packed',
  'm20.readyToPack': 'Picked, ready to pack',
  'm20.empty': 'Nothing to pick or pack',
  'm20.pickedOk': 'Pick recorded',
  'm20.packedOk': 'Packed',
  'm20.shortPick': 'Short picked',

  // --- M7 Load-out and challans (the manager's PIN) -------------------------------------------------
  'm7.tab': 'Load-out',
  'm7.title': 'Load-out & challans',
  'm7.sheets': 'Load sheets',
  'm7.challans': 'Challans',
  'm7.sheetDate': 'Date',
  'm7.vehicle': 'Vehicle',
  'm7.status': 'State',
  'm7.orders': 'Orders',
  'm7.packages': 'Packages',
  'm7.counted': 'Counted',
  'm7.loadValue': 'On board ₹',
  'm7.approve': 'Approve the load-out',
  'm7.approveTitle': 'Approve the load-out',
  'm7.pinHint':
    'Your approval IS the PIN, and it is given here — nothing is typed on the warehouse phone but the count.',
  'm7.pinBody':
    'The godown cannot check the vehicle out until you approve. Any difference between your expected packages and the crew’s count comes back to you.',
  'm7.approveNote': 'Note for the godown',
  'm7.approved': 'Approved · the godown may check it out',
  'm7.approvedBy': 'Approved by {name}',
  'm7.waitingForYou': 'Waiting for your approval',
  'm7.cancelSheet': 'Cancel the sheet',
  'm7.cancelReason': 'Why is it cancelled?',
  'm7.ewbRequired': 'E-way bill needed',
  'm7.ewbNo': 'E-way bill no.',
  'm7.recordEwb': 'Record the e-way bill',
  'm7.ewbHint': 'Type the number from the government portal.',
  'm7.challanNo': 'Challan no.',
  'm7.printChallan': 'Print the challan',
  'm7.empty': 'No load sheet today',
  'm7.detail': 'Load sheet · {vehicle}',
  'm7.from': 'From',
  'm7.to': 'To',
  'm7.confirmedAt': 'Checked out',
  'm7.noBill': 'No bill yet',
  'm7.alreadyApproved': 'This sheet is already approved',
  'm7.onlyDraft': 'Only a draft sheet can be cancelled',

  // --- M6 Billing desk -----------------------------------------------------------------------------
  'm6.tab': 'Billing desk',
  'm6.title': 'Billing desk',
  'm6.remaining': '{count} left to bill',
  'm6.queueRows': '{count} confirmed orders',
  'm6.packRows': '{count} packs already gone out',
  'm6.orderNo': 'Order',
  'm6.shop': 'Shop',
  'm6.value': 'Amount ₹',
  'm6.linesCount': 'Lines',
  'm6.state': 'State',
  'm6.expected': 'Wanted by',
  'm6.billPack': 'Issue the bill',
  'm6.billPackBody': 'Stock has already left. This issues the bill for that pack.',
  'm6.packs': 'Packed, not billed',
  'm6.invoices': 'Bills issued',
  'm6.invoiceNo': 'Bill no.',
  'm6.issuedAt': 'Issued',
  'm6.due': 'Still due ₹',
  'm6.payState': 'Payment',
  'm6.print': 'Print the bill',
  'm6.pdfQueued': 'The bill is being printed. Try again in a moment.',
  'm6.cancelInvoice': 'Cancel the bill',
  'm6.cancelBody': 'The number is kept. Stock and money come back. Only before dispatch.',
  'm6.cancelReason': 'Why is it cancelled?',
  'm6.setEwb': 'Record the e-way bill',
  'm6.requestIrn': 'Get the IRN',
  'm6.irn': 'IRN',
  'm6.empty': 'Nothing waiting to be billed',
  'm6.noInvoices': 'No bill in this window',
  'm6.detail': 'Bill {no}',
  'm6.buyer': 'Shop',
  'm6.taxable': 'Taxable ₹',
  'm6.gst': 'GST ₹',
  'm6.total': 'Total ₹',
  'm6.nextBill': 'Next bill',
  'm6.keys': 'j / k move · Enter open · p print',
  'm6.alreadyCancelled': 'This bill is already cancelled',

  // --- M8 Credit notes -----------------------------------------------------------------------------
  'm8.tab': 'Credit notes',
  'm8.title': 'Credit notes',
  'm8.noteNo': 'Note no.',
  'm8.shop': 'Shop',
  'm8.against': 'Against bill',
  'm8.reason': 'Why',
  'm8.value': 'Amount ₹',
  'm8.status': 'State',
  'm8.issuedAt': 'Issued',
  'm8.issue': 'Issue the note',
  'm8.draft': 'Draft a credit note',
  'm8.issueBody': 'The number is allotted, the pieces go back into stock and the shop is credited.',
  'm8.cancel': 'Cancel the draft',
  'm8.empty': 'No credit note in this window',
  'm8.detail': 'Credit note {no}',
  'm8.lines': 'Lines',
  'm8.onlyDraft': 'Only a draft note can be issued or cancelled',

  // --- M11 Brand-DMS bills -------------------------------------------------------------------------
  'm11.tab': 'Brand DMS',
  'm11.title': 'Brand DMS bills',
  'm11.hint':
    'Too Yumm bills on FieldAssist. We store the brand’s own bill as it is — never a second legal document.',
  'm11.invoiceNo': 'Their bill no.',
  'm11.shop': 'Shop',
  'm11.date': 'Bill date',
  'm11.value': 'Amount ₹',
  'm11.source': 'Source',
  'm11.capture': 'Photograph the bill',
  'm11.import': 'Import a FieldAssist file',
  'm11.empty': 'No brand bill imported yet',

  // --- M9 Receipts and allocations -----------------------------------------------------------------
  'm9.tab': 'Receipts',
  'm9.title': 'Receipts',
  'm9.receiptNo': 'Receipt no.',
  'm9.shop': 'Shop',
  'm9.mode': 'Mode',
  'm9.amount': 'Amount ₹',
  'm9.unallocated': 'On account ₹',
  'm9.status': 'State',
  'm9.receivedAt': 'Received',
  'm9.receivedBy': 'Taken by',
  'm9.record': 'Record a payment',
  'm9.recordTitle': 'Money from a shop',
  'm9.pickShop': 'Which shop?',
  'm9.amountLabel': 'How much came in?',
  'm9.modeLabel': 'How did it come in?',
  'm9.reference': 'Reference',
  'm9.chequeDate': 'Cheque date',
  'm9.bankName': 'Bank',
  'm9.upiVpa': 'UPI id',
  'm9.allocate': 'Put it against bills',
  'm9.allocateHint': 'Oldest bill first unless you say otherwise.',
  'm9.openBills': 'Open bills',
  'm9.removeAllocation': 'Undo this allocation',
  'm9.reverse': 'Reverse the receipt',
  'm9.reverseBody': 'A mirror receipt is written. The original is never edited.',
  'm9.reverseReason': 'Why is it reversed?',
  'm9.share': 'Send the receipt',
  'm9.print': 'Print the receipt',
  'm9.upiQr': 'Show the UPI code',
  'm9.empty': 'No receipt in this window',
  'm9.detail': 'Receipt {no}',
  'm9.allocations': 'Put against',
  'm9.owes': 'Owes {amount}',
  'm9.recorded': 'Receipt recorded',
  'm9.needsShop': 'Pick a shop first',
  'm9.needsAmount': 'Enter the amount',
  'm9.alreadyCancelled': 'This receipt is already cancelled',

  // --- M10 Day-end: banking, cheques, trip settlement ------------------------------------------------
  'm10.tab': 'Day-end',
  'm10.title': 'Day-end',
  'm10.toBank': 'Cash and cheques in hand',
  'm10.deposit': 'Bank this batch',
  'm10.ticked': 'To bank',
  'm10.depositTitle': 'Bank the day',
  'm10.depositRef': 'Bank slip number',
  'm10.depositAccount': 'Into which account?',
  'm10.depositBody': 'Every ticked receipt is marked banked with this slip number.',
  'm10.deposited': 'Banked',
  'm10.bounce': 'Return a bounced cheque',
  'm10.bounceTitle': 'Cheque returned',
  'm10.bounceReason': 'What did the bank say?',
  'm10.bankCharges': 'Bank charges',
  'm10.bounceBody': "The shop's outstanding comes back exactly as it was.",
  'm10.trips': 'Trips coming back',
  'm10.tripNo': 'Trip',
  'm10.vehicle': 'Vehicle',
  'm10.driver': 'Driver',
  'm10.stops': 'Stops',
  'm10.expectedCash': 'Expected ₹',
  'm10.countedCash': 'Handed over ₹',
  'm10.variance': 'Difference ₹',
  'm10.settle': 'Settle the trip',
  'm10.settleTitle': 'Check the van back in',
  'm10.settleBody':
    'Count the cash and the stock coming back. A difference beyond the tolerance goes to the owner.',
  'm10.collections': 'Collected on the road',
  'm10.expenses': 'Expenses',
  'm10.acceptVariance': 'Ask the owner to accept the difference',
  'm10.selected': '{count} receipts · {amount}',
  'm10.empty': 'Nothing to bank',
  'm10.noTrips': 'No trip is waiting to be settled',
  'm10.cheques': 'Cheques in hand',
  'm10.settled': 'Trip settled',
  'm10.needsRef': 'Enter the bank slip number',
  'm10.tolerance': 'Tolerance {amount}',

  // --- M17 Claims ------------------------------------------------------------------------------------
  'm17.tab': 'Claims',
  'm17.title': 'Claims on brands',
  'm17.claimNo': 'Claim no.',
  'm17.supplier': 'Supplier',
  'm17.brand': 'Brand',
  'm17.kind': 'Kind',
  'm17.period': 'Period',
  'm17.claimed': 'Claimed ₹',
  'm17.settled': 'Settled ₹',
  'm17.status': 'State',
  'm17.open': 'Open a claim',
  'm17.build': 'Build the lines',
  'm17.buildBody': 'The lines are rebuilt from bills, credit notes, the stock ledger and findings.',
  'm17.submit': 'Submit the claim',
  'm17.submitBody': 'The claim gets its number and the receivable is accrued.',
  'm17.acknowledge': 'Brand acknowledged it',
  'm17.settlement': 'Record a settlement',
  'm17.rejectClaim': 'The brand refused',
  'm17.writeOff': 'Write off the balance',
  'm17.statement': 'Make the claim sheet',
  'm17.ageing': 'Ageing',
  'm17.register': 'Register',
  'm17.recovery': 'Recovered',
  'm17.lines': 'Lines',
  'm17.evidence': 'Evidence',
  'm17.alreadyClaimed': 'Claimed · {state}',
  'm17.empty': 'No claim yet',
  'm17.detail': 'Claim {no}',
  'm17.periods': 'What is due to be claimed',
  'm17.dueValue': 'Worth ₹',
  'm17.onlyDraft': 'Only a draft claim can be built or submitted',
  'm17.notSubmitted': 'Submit the claim before recording a settlement',
  'm17.nothingOpen': 'Nothing is left to write off',

  // --- M12 Registers (the accountant's home) ---------------------------------------------------------
  'm12.tab': 'Registers',
  'm12.title': 'Registers',
  'm12.sales': 'Sales register',
  'm12.gst': 'GST summary',
  'm12.purchase': 'Purchase register',
  'm12.collections': 'Collections',
  'm12.outstanding': 'Outstanding',
  'm12.trial': 'Trial balance',
  'm12.dayBook': 'Day book',
  'm12.daily': 'Daily sales',
  'm12.gstr1Due': 'GSTR-1 for {month} is due on the 11th — {days} days left',
  'm12.gstr1DueToday': 'GSTR-1 for {month} is due today',
  'm12.gstr1Late': 'GSTR-1 for {month} was due {days} days ago',
  'm12.invoiceNo': 'Bill no.',
  'm12.shop': 'Shop',
  'm12.date': 'Date',
  'm12.taxable': 'Taxable ₹',
  'm12.gstAmount': 'GST ₹',
  'm12.total': 'Total ₹',
  'm12.rate': 'Rate',
  'm12.hsn': 'HSN',
  'm12.account': 'Account',
  'm12.debit': 'Debit ₹',
  'm12.entryValue': 'Value ₹',
  'm12.credit': 'Credit ₹',
  'm12.entryNo': 'Entry',
  'm12.narration': 'Narration',
  'm12.document': 'Document',
  'm12.mode': 'Mode',
  'm12.collected': 'Collected ₹',
  'm12.bucket': 'Age',
  'm12.owed': 'Owed ₹',
  'm12.empty': 'Nothing in this window',
  'm12.byRate': 'By rate',
  'm12.byHsn': 'By HSN',
  'm12.creditNotes': 'Credit notes, reported apart',

  // --- M13 Tally export and mapping -------------------------------------------------------------------
  'm13.tab': 'Tally',
  'm13.title': 'Tally export',
  'm13.exports': 'Export jobs',
  'm13.mappings': 'Names in Tally',
  'm13.syncLedger': 'Already pushed',
  'm13.kind': 'What',
  'm13.status': 'State',
  'm13.requestedAt': 'Asked for',
  'm13.download': 'Download',
  'm13.rows': 'Rows',
  'm13.queue': 'Queue an export',
  'm13.queueTitle': 'Queue a Tally export',
  'm13.entity': 'Ours',
  'm13.tallyName': 'Called in Tally',
  'm13.tallyParent': 'Under',
  'm13.setName': 'Set the Tally name',
  'm13.document': 'Document',
  'm13.docType': 'What',
  'm13.guid': 'Tally GUID',
  'm13.pushedAt': 'Pushed',
  'm13.empty': 'Nothing exported yet',
  'm13.noMappings': 'No name is mapped yet',

  // --- M21 Team performance ----------------------------------------------------------------------------
  'm21.tab': 'Team',
  'm21.title': 'Team performance',
  'm21.rep': 'Person',
  'm21.beat': 'Beat',
  'm21.visits': 'Visits',
  'm21.orders': 'Orders',
  'm21.strikeRate': 'Strike rate',
  'm21.value': 'Order value ₹',
  'm21.lapsed': 'Shops being lost',
  'm21.risk': 'Risk',
  'm21.lastOrder': 'Last order',
  'm21.ofTarget': 'Of each target',
  'm21.targets': 'Targets',
  'm21.achieved': 'Achieved',
  'm21.leaderboard': 'Leaderboard',
  'm21.metric': 'Metric',
  'm21.empty': 'No figure for this window',
  'm21.strikeChart': 'Strike rate by person',

  // --- M14 Shops and credit -----------------------------------------------------------------------------
  'm14.title': 'Shops',
  'm14.code': 'Code',
  'm14.name': 'Shop',
  'm14.beat': 'Beat',
  'm14.tier': 'Tier',
  'm14.terms': 'Terms',
  'm14.owes': 'Owes ₹',
  'm14.limit': 'Limit ₹',
  'm14.phone': 'Phone',
  'm14.gstin': 'GSTIN',
  'm14.setCredit': 'Change the credit terms',
  'm14.creditTitle': 'Credit for {shop}',
  'm14.creditLimit': 'Credit limit',
  'm14.creditDays': 'Days to pay',
  'm14.creditMode': 'Over the limit',
  'm14.statement': 'Send the statement',
  'm14.statementBody': 'The statement is queued and sent on WhatsApp.',
  'm14.ledger': 'Statement of account',
  'm14.bills': 'Bills',
  'm14.link': 'Link the shopkeeper',
  'm14.linkPhone': 'Their phone number',
  'm14.linkBody': 'The shopkeeper can then sign in and see their own bills.',
  'm14.empty': 'No shop matches',
  'm14.detail': '{shop}',
  'm14.balance': 'Balance ₹',
  'm14.entry': 'What',
  'm14.oldest': 'Oldest bill',
  'm14.behaviour': 'How they buy',
  'm14.avgDays': 'Usually pays in {days} days',
  'm14.lastOrderOn': 'Last order {when}',

  // --- M16 Stock -----------------------------------------------------------------------------------------
  'm16.title': 'Stock',
  'm16.balances': 'On hand',
  'm16.ledger': 'Stock ledger',
  'm16.counts': 'Cycle counts',
  'm16.item': 'Item',
  'm16.lot': 'Batch',
  'm16.location': 'Where',
  'm16.onHand': 'On hand',
  'm16.reserved': 'Held',
  'm16.available': 'Free',
  'm16.expiry': 'Expires',
  'm16.mrp': 'MRP ₹',
  'm16.when': 'When',
  'm16.reason': 'Why',
  'm16.qty': 'Pieces',
  'm16.adjust': 'Adjust the stock',
  'm16.adjustTitle': 'Adjust stock',
  'm16.adjustReason': 'Why is it being adjusted?',
  'm16.transfer': 'Move stock',
  'm16.transferTitle': 'Move stock between places',
  'm16.transferFrom': 'From',
  'm16.transferTo': 'To',
  'm16.nearExpiry': 'Near expiry',
  'm16.empty': 'No stock row',
  'm16.reservationsTitle': 'Held for orders',
  'm16.countStatus': 'State',
  'm16.expected': 'Expected',
  'm16.counted': 'Counted',

  // --- M15 Prices and schemes ------------------------------------------------------------------------------
  'm15.title': 'Prices & schemes',
  'm15.priceLists': 'Price lists',
  'm15.schemes': 'Schemes',
  'm15.overrides': 'Shop rates',
  'm15.listName': 'List',
  'm15.tier': 'Tier',
  'm15.validFromMeta': 'From {date}',
  'm15.validFrom': 'From',
  'm15.validTo': 'To',
  'm15.items': 'Items',
  'm15.schemeName': 'Scheme',
  'm15.trigger': 'Applies when',
  'm15.reward': 'Gives',
  'm15.funding': 'Paid by',
  'm15.priority': 'Order',
  'm15.exclusive': 'On its own',
  'm15.stacks': 'Stacks',
  'm15.item': 'Item',
  'm15.claimable': 'Claimable',
  'm15.active': 'Running',
  'm15.shop': 'Shop',
  'm15.rate': 'Rate ₹',
  'm15.final': 'Final rate',
  'm15.triggerQty': 'Quantity ≥ {count} pc',
  'm15.triggerValue': 'Order value ≥ {amount}',
  'm15.triggerAlways': 'Always',
  'm15.rewardPct': '{label}: {pct}',
  'm15.rewardAmount': '{label}: {amount}',
  'm15.rewardFree': '{count} free',
  'm15.empty': 'Nothing set up yet',
  'm15.readOnly': 'Prices and schemes are set by the owner or the manager.',

  // --- M18 Messages ------------------------------------------------------------------------------------------
  'm18.title': 'Messages',
  'm18.outbox': 'Sent',
  'm18.inbound': 'Shops wrote to us',
  'm18.templates': 'Wording',
  'm18.broadcasts': 'Broadcasts',
  'm18.channel': 'Channel',
  'm18.shop': 'Shop',
  'm18.template': 'What',
  'm18.status': 'State',
  'm18.sentAt': 'Sent',
  'm18.attempts': 'Tries',
  'm18.resend': 'Send it again',
  'm18.body': 'Wording',
  'm18.language': 'Language',
  'm18.saveTemplate': 'Save the wording',
  'm18.broadcast': 'Send to a beat',
  'm18.broadcastTitle': 'Send to every shop on a beat',
  'm18.pickBeat': 'Which beat?',
  'm18.pickTemplate': 'Which message?',
  'm18.recipients': 'Shops',
  'm18.delivered': 'Delivered',
  'm18.failed': 'Failed',
  'm18.markHandled': 'Mark it handled',
  'm18.received': 'Received',
  'm18.text': 'What they wrote',
  'm18.empty': 'Nothing here yet',
  'm18.defaultWording': 'Platform wording',
  'm18.ownWording': 'Our own wording',
  // --- shared vocabulary ---------------------------------------------------------------------------------------------------
  'word.beat': 'Beat',
  'word.rep': 'Rep',
  'word.brand': 'Brand',
  'word.all': 'All',
  'word.active': 'Active',
  'word.pending': 'Pending',
  'word.yes': 'Yes',
  'word.no': 'No',
  'word.total': 'Total',
  'word.count': 'Count',

  /*
   * --- the services' own enum values, in the trade's words (`src/lib/words.ts`) -------------------
   *
   * `useWord()` looks a value up as `word.<value>`; a value with no key here is humanised
   * (`partly_settled` -> "Partly settled"), so this list carries only the ones where the machine word
   * and the shop's word differ, or where an initialism must stay upright (UPI, GST, POD, GRN).
   * Values shared by two enums are spelled the way BOTH read correctly.
   */

  // order + trip + stop states
  'word.partially_delivered': 'Part delivered',
  'word.settled_with_variance': 'Settled, variance',
  'word.return_undelivered': 'Returned to godown',

  // approvals
  'word.credit_limit': 'Over credit limit',
  'word.below_floor': 'Below floor price',
  'word.manual_price': 'Price changed by hand',
  'word.scheme_override': 'Scheme overridden',
  /* One value, one word: this is the approval kind AND the day book's journal reference. */
  'word.trip_settlement': 'Trip settlement',

  // invoices and credit notes
  'word.partially_paid': 'Part paid',
  'word.written_off': 'Written off',
  'word.short_delivery': 'Short delivered',
  'word.return_saleable': 'Return, saleable',
  'word.return_damaged': 'Return, damaged',
  'word.rate_difference': 'Rate difference',
  'word.scheme_settlement': 'Scheme settlement',
  'word.brand_dms_import': 'Brand DMS import',
  // `SupplierInvoiceSourceSchema`. `docint` is our module's name, not a word a distributor uses:
  // the inbound register's Source column read "Docint" beside "Manual entry".
  'word.docint': 'Read off the bill',
  'word.irn_pull': 'Pulled from the IRN',
  'word.import': 'Bulk import',
  'word.b2b': 'B2B',
  'word.B2B': 'B2B',
  'word.b2c': 'B2C',
  'word.B2C': 'B2C',

  // money
  'word.upi': 'UPI',
  'word.bank_transfer': 'Bank transfer',
  'word.on_account': 'On account',
  'word.at_receipt_financial_cn': 'Credit note at receipt',
  'word.on_invoice': 'On the invoice',
  'word.PRE': 'Pays in advance',
  'word.ON': 'Pays on delivery',
  'word.POST_FULFILLMENT': 'Credit',
  'word.indicate': 'Warn only',
  'word.strict': 'Needs approval',
  'word.stop': 'Blocked',

  // stock and inbound — the stock ledger's own reasons (`inventory.StockReasonSchema`).
  'word.grn': 'GRN',
  'word.sale': 'Sold',
  'word.sale_return_saleable': 'Returned, saleable',
  'word.sale_return_damaged': 'Returned, damaged',
  'word.damage': 'Damaged',
  'word.expiry_writeoff': 'Expired',
  'word.transfer_out': 'Sent out',
  'word.transfer_in': 'Brought in',
  'word.van_load': 'Loaded on a van',
  'word.van_unload': 'Unloaded from a van',
  'word.adjustment': 'Adjusted by hand',
  'word.fefo_override': 'FEFO overridden',
  'word.needs_review': 'Needs review',
  'word.mrp': 'MRP',
  'word.ptd': 'PTD',
  'word.hsn': 'HSN',
  'word.pod': 'POD',
  'word.gps.live_map_read': 'GPS live map read',
  'word.gps.trace_read': 'GPS trace read',
  'word.gps.points_write': 'GPS points written',
  'word.credit_only': 'Credit bills only',
  'word.always': 'Every bill',
  'word.never': 'Never',

  // people
  'word.salesperson': 'Salesperson',
  'word.platform_admin': 'Distribution OS staff',
  'word.must_change_password': 'Temporary password',

  // imports and exports
  'word.tradeezee': 'TradeEzee',
  'word.fieldassist': 'FieldAssist',
  'word.tally_xml': 'Tally XML',
  'word.gstr1_json': 'GSTR-1 JSON',
  'word.sales_register_xlsx': 'Sales register (Excel)',
  'word.outstanding_xlsx': 'Outstanding (Excel)',
  'word.eway_bill_json': 'E-way bill JSON',
  'word.einvoice_json': 'E-invoice JSON',
  'word.claim_sheet': 'Claim sheet',
  // The `report_<register>_csv` family of `integrations.exports`. Without these the export register
  // read "Report gst sales register csv" beside "Tally XML" and "Outstanding (Excel)" — one column,
  // two languages, ours and the database's.
  'word.report_gstSalesRegister_csv': 'GST sales register (CSV)',
  'word.report_gstPurchaseRegister_csv': 'GST purchase register (CSV)',
  'word.report_dailySales_csv': 'Daily sales (CSV)',
  'word.report_stockValue_csv': 'Stock value (CSV)',
  'word.report_fillRate_csv': 'Fill rate (CSV)',
  'word.report_repProductivity_csv': 'Rep productivity (CSV)',
  'word.report_schemeSpend_csv': 'Scheme spend (CSV)',
  'word.report_collections_csv': 'Collections (CSV)',
  'word.report_deliveryPerformance_csv': 'Delivery performance (CSV)',
  'word.gstSalesRegister': 'GST sales register',
  'word.gstPurchaseRegister': 'GST purchase register',
  'word.dailySales': 'Daily sales',
  'word.repProductivity': 'Rep productivity',
  'word.schemeSpend': 'Scheme spend',
  'word.stockValue': 'Stock value',
  'word.fillRate': 'Fill rate',
  'word.deliveryPerformance': 'Delivery performance',
  'word.opening_outstanding': 'Opening outstanding',
  'word.party_master': 'Shops',
  'word.item_master': 'Items',
  'word.sales_register': 'Sales register',
  'word.brand_dms_invoices': 'Brand DMS bills',
  'word.rolled_back': 'Rolled back',

  // messages
  /* The locale tag is a machine word too: a template's Language column read `en-IN`. */
  'word.en-IN': 'English',
  'word.hi-IN': 'Hindi',
  'word.mr-IN': 'Marathi',
  'word.sms': 'SMS',
  'word.in_app': 'In the app',
  'word.pod_delivered': 'Delivery proof',
  'word.payment_received': 'Payment received',
  'word.order_confirmed': 'Order confirmed',
  'word.invoice_issued': 'Bill issued',
  'word.dues_reminder': 'Dues reminder',
  'word.scheme_announcement': 'Scheme announcement',

  // Chart series: `reporting.series.*` names its metrics in code, the screen names them in words.
  'word.invoiced': 'Invoiced',
  'word.collected': 'Collected',
  'word.outstanding': 'Money owed',
  'word.overdue': 'Overdue',
  'word.deliveredStops': 'Stops delivered',
  'word.partialStops': 'Part delivered',
  'word.failedStops': 'Not delivered',
  'word.onTimeRate': 'On time',
  'word.podCoverageRate': 'Proof taken',
  'word.nearExpiryValue': 'Near expiry',
  'word.stockTurns': 'Stock turns',
  'word.grossMargin': 'Gross margin',

  // Scheme economics (pricing.schemes) — the words a distributor uses for the same rows.
  'word.qty': 'Quantity',
  'word.value': 'Order value',
  'word.mix': 'Mixed',
  /* The trade's own abbreviations, which UX-00 section 4.5 rule 7 already uses ("2 cs + 6 pc"), so a
     count of one does not have to read "1 pieces". */
  'word.pcs': 'pc',
  'word.case': 'cs',
  'word.line_pct': 'Off the line',
  'word.order_pct': 'Off the bill',
  'word.cash_discount_pct': 'Cash discount',
  'word.net_scheme_amount': 'Flat scheme amount',
  'word.company': 'The brand',
  'word.distributor': 'Us',

  // Journal reference types (the day book's Document column). `trip_settlement` already has a word
  // above, where it is an approval kind; one value keeps one word.
  'word.claim_settlement': 'Claim settled',
  'word.claim_write_off': 'Claim written off',
  'word.receipt_reversal': 'Receipt reversed',
  'word.invoice_cancel': 'Bill cancelled',
  'word.load_sheet': 'Load sheet',
  'word.cycle_count': 'Cycle count',
  'word.trip_stop': 'Delivery stop',
  'word.writeoff': 'Written off',
  'word.opening': 'Opening balance',
  'word.manual': 'Manual entry',

  // Numbering series allocation, feature flags and the support desk's access scope.
  'word.server': 'We allot it',
  'word.device': 'The device allots it',
  'word.external': 'It comes on the supplier bill',
  'word.van_sales': 'Van sales',
  'word.claims_ui': 'Claims screens',
  'word.retailer_app': 'Shopkeeper app',
  'word.e_invoicing': 'E-invoicing',
  'word.read_only': 'Read only',
  'word.read_write': 'Read and change',

  // Incentive target metrics.
  'word.pieces': 'Pieces',
  'word.outlets': 'Shops billed',
  'word.visits': 'Beat visits',
  'word.collections': 'Money collected',

  // Message templates the platform ships (notifications.templates).
  'word.order_needs_approval': 'Order needs approval',
  'word.welcome': 'Welcome',

  // schemes and visits
  'word.free_qty': 'Free goods',
  'word.no_order': 'No order',
  'word.not_found': 'Shop not found',
  'word.payment_only': 'Payment only',

  /*
   * --- the enum values the OWNER app never had to name --------------------------------------------
   *
   * Everything above is the vocabulary the two desk apps share. These are the machine words that only
   * reach a screen in the back office: picking, packing, loading, gate counts, document review,
   * claims and Tally. Same rule as above — a value with no key here is humanised by the kit, so this
   * list carries only the ones where the enum and the trade disagree, or where an initialism must
   * stay upright.
   */

  // picklists, packs, load sheets (warehouse.*)
  'word.open': 'Open',
  'word.picking': 'Being picked',
  'word.picked': 'Picked',
  'word.packed': 'Packed',
  'word.short_picked': 'Short picked',
  'word.draft': 'Draft',
  'word.confirmed': 'Confirmed',
  'word.checked_out': 'Checked out',

  // goods receipt and its findings (procurement.*)
  'word.counting': 'Being counted',
  'word.short': 'Short received',
  'word.excess': 'Extra received',
  'word.damaged': 'Damaged',
  'word.claimed': 'Claimed from the brand',
  'word.credited': 'Supplier credited us',
  'word.accepted': 'Accepted',
  'word.disputed': 'Disputed',
  'word.received': 'Received',
  'word.matched': 'Matched',
  'word.unmatched': 'Not matched',

  // document intake (docint.*)
  'word.supplier_invoice': 'Supplier bill',
  'word.brand_dms_invoice': 'Brand DMS bill',
  'word.lorry_receipt': 'Lorry receipt',
  'word.capturing': 'Being photographed',
  'word.queued': 'Waiting',
  'word.extracting': 'Being read',
  'word.in_review': 'Being reviewed',
  'word.reviewed': 'Reviewed',
  'word.committed': 'Booked',
  'word.decoded': 'QR read',
  'word.no_qr': 'No QR on the bill',
  'word.undecodable': 'QR unreadable',
  'word.duplicate': 'Already have this bill',
  'word.qr': 'QR',
  'word.irn': 'IRN',
  'word.llm_vision': 'Read from the photograph',
  'word.structured_pull': 'Pulled from the portal',
  'word.alias': 'Remembered name',
  'word.trigram': 'Name match',
  'word.barcode': 'Barcode',
  'word.manual_choice': 'Chosen by hand',

  // claims (claims.*)
  'word.damages': 'Damages',
  'word.expiry': 'Expiry',
  'word.scheme': 'Scheme',
  'word.rate_diff': 'Rate difference',
  'word.acknowledged': 'Brand acknowledged',
  'word.part_settled': 'Part settled',
  'word.goods': 'Replaced with goods',
  'word.credit_note': 'Credit note',
  'word.bank_receipt': 'Money in the bank',
  'word.cheque': 'Cheque',

  // AI drafts (ai.*)
  'word.whatsapp': 'WhatsApp',
  'word.voice': 'Voice note',
  'word.expired': 'Too old to use',

  // Tally and export jobs (integrations.*)
  'word.ledger': 'Ledger',
  'word.stock_item': 'Item',
  'word.godown': 'Godown',
  'word.unit': 'Unit',
  'word.voucher_type': 'Voucher type',
  'word.party': 'Party',
  'word.rendered': 'Ready',
  'word.gst_summary': 'GST summary',

  // deposits and cheque returns (receivables.*)
  'word.deposited': 'Banked',
  'word.bounced': 'Bounced',
  'word.reversed': 'Reversed',
  'word.collected_money': 'In hand',
} as const
