import * as A from './wh-lib.mjs'
await A.newSession()
await A.sleep(1500)
await A.dismissSystemDialogs()
A.log('home:', await A.texts(1200))
await A.tapId('w1-wave-7ff186e1-aa5c-76f5-9038-2d464dfb22a2', { timeout: 30000 })
await A.sleep(4000)
await A.shot('wh-03-pick-sheet-online')
A.log('sheet:', await A.texts(2500))
const xml = await A.source()
const picks = [...xml.matchAll(/resource-id="(w5-pick-[^"]+)"/g)].map((m) => m[1])
const lines = [...xml.matchAll(/resource-id="(w5-line-[^"]+)"/g)].map((m) => m[1])
A.log('pick buttons on screen:', JSON.stringify(picks))
A.log('line rows on screen:', JSON.stringify(lines))
A.log('sqlite:\n' + A.sqliteFiles())
await A.quit()
