/**
 * The words of the desk's pricing and credit editors (DOS-212, DOS-214), shared by the owner and the
 * manager groups.
 *
 * Strings are SWAPPED per group, never merged (docs/31 §3): each group's record spreads this one in, so
 * both desks carry exactly the same sentences for the same editors and neither can drift. Every key is
 * `px.*`, a prefix no group used before, so the spread cannot shadow a group's own word.
 *
 * Writing rules (UX-00 §12): the trade's own word, buttons are verb + object, a problem states the next
 * action, never "!" and never an emoji.
 */
export const PRICING_STRINGS = {
  // --- DOS-212 credit -------------------------------------------------------------------------------------------
  'px.creditTitle': 'Credit for {shop}',
  'px.creditLimit': 'Credit limit',
  'px.creditDays': 'Days to pay',
  'px.creditNow': 'Now: {limit} · {days} days · {mode} · {terms}',
  'px.creditMode': 'Over the limit',
  'px.creditModeHelp.indicate': 'The order goes through; the rep and the desk see a warning.',
  'px.creditModeHelp.strict': 'An order over the limit waits for the owner or the manager.',
  'px.creditModeHelp.stop': 'No new order on credit; take the money before the goods go.',
  'px.terms': 'Payment terms',
  'px.termsHelp.PRE': 'The shop pays before the order is packed.',
  'px.termsHelp.ON': 'The shop pays the crew at the door.',
  'px.termsHelp.POST_FULFILLMENT': 'The shop pays within its credit days.',
  'px.saveCredit': 'Save the terms',
  'px.nothingChanged': 'Change something first',
  'px.creditSaved': 'Credit terms saved',
  'px.needLimit': 'Enter a credit limit (₹0 for no credit)',
  'px.needDays': 'Enter the days to pay, 0 to 365',

  // --- DOS-214 price lists --------------------------------------------------------------------------------------
  'px.changeRate': 'Change the rate',
  'px.addItem': 'Add an item',
  'px.addItemTitle': 'Add an item to {list}',
  'px.rateNow': 'Now {rate} on {list}',
  'px.newRate': 'New rate per piece',
  'px.gst': 'The rate',
  'px.gstExcluded': 'Before GST',
  'px.gstIncluded': 'Includes GST',
  'px.saveRate': 'Save the rate',
  'px.rateSaved': 'Rate saved',
  'px.rateApplies':
    'New orders are priced at this rate from now. Orders already placed keep the price they were given.',
  'px.tapToEdit': 'Pick a row to change it.',
  'px.findItem': 'Find the item',
  'px.findItemHelp': 'Type part of the name, then pick it below.',
  'px.noItemMatch': 'No item matches. Check the spelling.',
  'px.pickedItem': 'Item: {name}',
  'px.pickedShop': 'Shop: {name}',
  'px.alreadyOnList': 'Already on this list at {rate}. Saving changes that rate.',
  'px.needItem': 'Pick the item first',
  'px.needRate': 'Enter a rate above ₹0',

  // --- DOS-214 shop rates (overrides) ---------------------------------------------------------------------------
  'px.setShopRate': 'Set a shop rate',
  'px.editShopRate': 'Shop rate',
  'px.findShop': 'Find the shop',
  'px.findShopHelp': 'Type part of the shop name or code.',
  'px.noShopMatch': 'No shop matches.',
  'px.shopRate': 'The shop’s rate per piece',
  'px.final': 'Schemes on top',
  'px.finalYes': 'Final, no scheme',
  'px.finalNo': 'Schemes may apply',
  'px.finalHelp': 'A final rate is the price. No scheme is taken off it.',
  'px.from': 'From (YYYY-MM-DD)',
  'px.to': 'Until (YYYY-MM-DD, empty = no end)',
  'px.toRequired': 'Until (YYYY-MM-DD)',
  'px.note': 'Why (optional)',
  'px.replaces': 'This shop already pays {rate} for this item. Saving replaces that rate.',
  'px.saveShopRate': 'Save the shop rate',
  'px.shopRateSaved': 'Shop rate saved',
  'px.endRate': 'End this rate',
  'px.endRateTitle': 'End the shop rate',
  'px.endRateBody': '{shop} pays the list price for {item} from {date}.',
  'px.rateEnded': 'Shop rate ended',
  'px.state.running': 'Running',
  'px.state.ended': 'Ended',
  'px.state.upcoming': 'Not started',
  'px.state.paused': 'Paused',
  'px.status': 'Status',
  'px.needShop': 'Pick the shop first',

  // --- DOS-214 schemes ------------------------------------------------------------------------------------------
  'px.newScheme': 'New scheme',
  'px.editScheme': 'Edit the scheme',
  'px.schemeName': 'Name on the scheme letter',
  'px.gives': 'What it gives',
  'px.reward.line_pct': '% off the item',
  'px.reward.order_pct': '% off the bill',
  'px.reward.free_qty': 'Free pieces',
  'px.reward.per_unit_amount': '₹ off each unit',
  'px.reward.net_scheme_amount': '₹ off per multiple',
  'px.reward.cash_discount_pct': 'Cash discount %',
  'px.percent': 'Discount %',
  'px.percentHelp': 'For 2.5 % type 2.5',
  'px.freePieces': 'Free pieces',
  'px.freeHelp': 'Pieces of the same item, given each time the rule is met',
  'px.amount': 'Amount off',
  'px.when': 'Applies when',
  'px.whenQty': 'Quantity',
  'px.whenValue': 'Bill value',
  'px.whenMix': 'Mix (kept as set)',
  'px.unit': 'Counted in',
  'px.unitPcs': 'Pieces',
  'px.unitCase': 'Cases',
  'px.atLeast': 'At least',
  'px.billAtLeast': 'Bill value at least',
  'px.on': 'On',
  'px.onAll': 'Every item',
  'px.onItems': 'Chosen items',
  'px.onKept': 'As set (brand)',
  'px.onKeptHelp': 'This scheme names a brand or a category. Saving keeps that as it is.',
  'px.itemsPicked': '{count} items chosen',
  'px.shops': 'Which shops',
  'px.shopsHelp': 'No tier picked = every shop.',
  'px.tier': 'Tier {tier}',
  'px.stacking': 'With other schemes',
  'px.stacks': 'Stacks',
  'px.exclusive': 'On its own',
  'px.exclusiveHelp':
    'On its own: the shop gets this scheme or the others together, whichever is worth more.',
  'px.paidBy': 'Paid by',
  'px.paidCompany': 'The brand',
  'px.paidUs': 'Us',
  'px.running': 'Running',
  'px.paused': 'Paused',
  'px.kept': 'Kept as set: {what}',
  'px.keptSlabs': 'slabs',
  'px.keptShops': 'named shops or beats',
  'px.keptClaim': 'the brand claim',
  'px.saveScheme': 'Save the scheme',
  'px.schemeSaved': 'Scheme saved',
  'px.cancel': 'Cancel',
  'px.needName': 'Give the scheme a name',
  'px.nameTooLong': 'Keep the name under 120 characters',
  'px.needPercent': 'Enter a percentage above 0 and up to 100, like 2.5',
  'px.needFree': 'Enter how many pieces are free',
  'px.needAmount': 'Enter the amount off, above ₹0',
  'px.needBillValue': 'Enter the bill value it starts at',
  'px.needCount': 'Enter the quantity it starts at, as a whole number',
  'px.perUnitNeedsUnit': '“₹ off each unit” needs a quantity trigger, not a bill value',
  'px.needItems': 'Pick at least one item, or choose Every item',
  'px.badFrom': 'Write the start date as YYYY-MM-DD',
  'px.badTo': 'Write the end date as YYYY-MM-DD',
  'px.toBeforeFrom': 'The end date is before the start date',
  'px.readOnly': 'Prices and schemes are set by the owner or the manager.',
} as const
