/**
 * This app's own string namespace, merged over the kit catalogue by `<ThemeProvider strings={...}>`.
 *
 * English only for the pilot (founder, 2026-09-05) — and every user-visible word already has a locale
 * key, so Hindi and Marathi are a translation file, never a rewrite. No component in this app
 * contains a literal English sentence.
 *
 * Keys are named after the screen in docs/23 §4.1 they belong to: `w1.*` is the home queue, `w3.*` is
 * the gate count, `w5.*` the picking sheet, and so on. `x*` are the four frame screens of §0.
 */
export const strings = {
  // ---------------------------------------------------------------- frame (docs/23 §0)
  'app.home': 'Inbound',
  'app.signIn': 'Sign in',
  'app.signInTitle': 'Sign in',
  'app.username': 'Username',
  'app.password': 'Password',
  'app.signInFailed': 'Could not sign in',
  'app.signInHint': 'The godown sign-in. Ask your manager for a username.',
  'app.signOut': 'Sign out',
  'app.distributor': 'Distributor',
  'app.role': 'Role',
  'app.person': 'Signed in as',
  'app.state': 'State',
  'app.changePassword': 'Change your password',
  'app.passwordForced':
    'This password was given to you by someone else. Set your own before you carry on.',
  'app.passwordVoluntary': 'Choose a new password for this account.',
  'app.currentPassword': 'Current password',
  'app.newPassword': 'New password',
  'app.repeatPassword': 'New password again',
  'app.passwordRule': 'At least 8 characters, with a letter and a digit',
  'app.passwordMismatch': 'The two new passwords are not the same',
  'app.passwordNeedsCurrent': 'Enter the password you signed in with',
  'app.passwordRevokes': 'Your other devices will be signed out.',
  'app.setPassword': 'Set password',
  'app.passwordFailed': 'Could not change the password',
  'app.settings': 'Me',
  'app.wrongRoleTitle': 'This app is for the godown',
  'app.wrongRoleBody':
    'You are signed in as {role}. The warehouse service answers only the warehouse role — sign out and use your own app.',

  // X4 profile and devices
  'x4.title': 'Me',
  'x4.devices': 'Signed-in devices',
  'x4.device': 'Device',
  'x4.lastSeen': 'Last used',
  'x4.revoke': 'Sign this one out',
  'x4.revokeBody': 'That device will have to sign in again. This one stays signed in.',
  'x4.otherDevice': 'Another device',
  'x4.noDevices': 'Only this device',
  'x4.inbox': 'Inbox',
  'x4.inboxEmpty': 'No messages',
  'x4.thisDevice': 'This device',
  'x4.storeMemory': 'Held in memory only — a reload empties this device',
  'x4.storeDisk': 'Held on this device',
  'x4.tables': '{count} tables on this device',
  'x4.tablesLabel': 'Tables on this device',
  'x4.pending': '{count} waiting to send',

  // ---------------------------------------------------------------- shared vocabulary
  'w.cases': '{cases} cs',
  'w.casesLoose': '{cases} cs + {loose} pc',
  'w.pieces': '{pieces} pc',
  /*
   * Countable fragments, singular and plural. `interpolate()` has no plural rule (it is a
   * placeholder substituter), and the kit's own catalogue therefore avoids "{count} filters" —
   * because the moment the count is 1 the screen reads "1 filters". These come in pairs and are
   * read through `pl()` in `src/lib/ui.tsx`, so Hindi and Marathi stay a translation job.
   */
  'w.linesN': '{count} lines',
  'w.linesN.one': '{count} line',
  'w.ordersN': '{count} orders',
  'w.ordersN.one': '{count} order',
  'w.cartonsN': '{count} cartons',
  'w.cartonsN.one': '{count} carton',
  'w.lotsN': '{count} lots',
  'w.lotsN.one': '{count} lot',
  'w.pagesN': '{count} pages captured',
  'w.pagesN.one': '{count} page captured',
  'w.pageNo': 'Page {page}',
  'w.batch': 'Batch {batch}',
  'w.noBatch': 'No batch',
  'w.expiry': 'Exp {date}',
  'w.noExpiry': 'No expiry',
  'w.expired': 'Expired {date}',
  'w.expiringDays': 'Expires in {days} days',
  'w.location': 'Location',
  'w.allLocations': 'Every location',
  'w.godown': 'Godown',
  'w.vehicle': 'Vehicle',
  'w.openScanner': 'Scan',
  'w.typeCode': 'Type code',
  'w.scanUnavailable': 'No camera on this device — type the code',
  'w.scanNothing': 'Nothing readable in frame',
  'w.scanned': 'Scanned {code}',
  'w.noMatch': 'Nothing on this sheet matches {code}',
  'w.saved': 'Saved',
  'w.savedOnDevice': 'Saved on this phone',
  'w.retry': 'Try again',
  'w.refresh': 'Refresh',
  'w.close': 'Close',
  'w.deskOnly': 'The desk does this',
  'w.filling': 'Still filling this phone from the server',
  'w.nothingHere': 'Nothing here yet',
  'w.unknownItem': 'Item not on this phone yet',
  /** Not read yet, or not readable: never a zero (UX-00 section 6.13). */
  'w.unknown': '\u2014',
  /*
   * A READ that failed for want of a signal, said as a read.
   *
   * `@dos/api-client`'s default sentence for `kind: 'network'` is "No connection. This will send
   * when the signal is back." — true of a queued WRITE and false of every panel on this screen,
   * which was asking, not sending. With warehouse-service stopped, six panels of the home queue and
   * three of the stock screen each promised to send something. `<Async>` is the read wrapper, so it
   * says the read sentence; a write keeps the client's own.
   */
  'w.noConnectionRead': 'No connection. This is not the current picture.',

  // ---------------------------------------------------------------- the tray (offline writes)
  'tray.title': 'Waiting and refused',
  'tray.waiting': 'WAITING TO SEND',
  'tray.waitingEmpty': 'Nothing is waiting',
  'tray.waitingCount': 'Waiting {count}',
  'tray.rejected': 'NEEDS YOU',
  'tray.rejectedEmpty': 'Nothing was refused',
  'tray.rejectedCount': 'Refused {count}',
  'tray.retry': 'Try it again',
  'tray.discard': 'Throw it away',

  // ---------------------------------------------------------------- W1 home queues
  'w1.title': 'Inbound',
  'w1.tab': 'Queues',
  'w1.grnsToCount': 'Bills to count',
  'w1.wavesOpen': 'Waves open',
  'w1.packsUnbilled': 'Packed, no bill',
  'w1.sheetsDraft': 'Sheets waiting',
  'w1.gateCounts': 'GATE COUNTS WAITING',
  'w1.gateCountsEmpty': 'Nothing at the gate',
  'w1.waves': 'WAVES ON THE FLOOR',
  'w1.wavesEmpty': 'No wave is being picked',
  'w1.packsQueue': 'PACKED WITHOUT A BILL',
  'w1.packsEmpty': 'Every pack has its bill',
  'w1.sheets': 'LOAD SHEETS',
  'w1.sheetsEmpty': 'No sheet waiting to go out',
  'w1.cycleCounts': 'COUNTS OPEN',
  'w1.fillRate': 'Fill rate, last 14 days',
  'w1.fillRateValue': '{percent}% of ordered pieces picked',
  'w1.countIt': 'Count it',
  'w1.receiptAt': 'Receipt at {location}',
  'w1.wavesMeta': '{picking} being picked · {open} waiting to start',
  /* A queue read one page at a time can only state a FLOOR; "20" when there are 200 is a lie. */
  'w1.atLeast': '{count}+',
  'w1.openWave': 'Open the sheet',

  // ---------------------------------------------------------------- W2 capture supplier bill
  'w2.title': 'Capture a bill',
  'w2.tab': 'Capture',
  'w2.body': 'Photograph every page of the supplier bill. Nothing else is typed here.',
  'w2.supplier': 'Supplier',
  'w2.supplierAny': 'Not sure yet',
  'w2.takePhoto': 'Photograph a page',
  'w2.pickFile': 'Choose a file',
  'w2.noPages': 'No page yet',
  'w2.scanQr': 'Scan the e-invoice QR',
  'w2.qrDone': 'QR read · {status}',
  'w2.qrDuplicate': 'This bill was already captured',
  'w2.submit': 'Send for reading',
  'w2.submitted': 'Sent',
  'w2.startFailed': 'Could not start the capture',
  'w2.pageFailed': 'Could not add that page',
  'w2.submitFailed': 'Could not send it',
  'w2.recent': 'RECENT CAPTURES',
  'w2.recentEmpty': 'Nothing captured yet',
  'w2.steps': 'THE FOUR STEPS',
  'w2.step1': 'QR / IRN checked',
  'w2.step2': 'Bill read',
  'w2.step3': 'Items matched',
  'w2.step4': 'Desk review',
  'w2.stepWaiting': 'Waiting',
  'w2.stepRunning': 'Running',
  'w2.stepDone': 'Done',
  'w2.stepFailed': 'Failed',
  'w2.reviewIsDesk': 'The desk reviews the reading and opens the GRN. You count at the gate.',
  'w2.watch': 'Watch it',
  'w2.byWhom': 'Captured by {name}',
  'w2.cameraDenied': 'Camera permission refused. Choose a file instead.',

  // ---------------------------------------------------------------- W3 gate count
  'w3.title': 'Gate count',
  'w3.context': 'Count what came off the lorry. The bill is not shown.',
  'w3.line': 'Line {index} of {total}',
  'w3.counted': 'Received',
  'w3.damaged': 'Damaged',
  'w3.countLabel': 'Pieces received',
  'w3.damagedLabel': 'Pieces damaged',
  'w3.next': 'Next line',
  'w3.done': 'Save the count',
  /* A button that only opens the review must not say it saves: the count would be lost. */
  'w3.review': 'Review the count',
  'w3.damagedNext': 'Damaged pieces',
  'w3.blind': 'Blind count: what the bill says is not on this screen.',
  'w3.saveFailed': 'Could not save the count',
  'w3.saved': 'Count saved',
  'w3.remaining': '{count} lines still to count',
  'w3.remaining.one': '{count} line still to count',
  'w3.allCounted': 'Every line counted',
  'w3.postIsDesk': 'The desk posts the GRN once the count is in.',
  'w3.notCounting': 'This receipt is {status} — nothing to count.',
  'w3.findings': 'FINDINGS',
  'w3.findingsEmpty': 'No short, excess or damage recorded',
  'w3.kindShort': 'Short',
  'w3.kindExcess': 'Excess',
  'w3.kindDamaged': 'Damaged',
  'w3.kindWrong': 'Wrong item',
  'w3.kindPrice': 'Price mismatch',
  'w3.kindExpiry': 'Near expiry',
  'w3.scanToJump': 'Scan a carton to jump to its line',

  // ---------------------------------------------------------------- W4 fulfilment queue
  'w4.title': 'Pick',
  'w4.tab': 'Queue',
  'w4.queue': 'ORDERS WAITING',
  'w4.queueEmpty': 'Nothing waiting to be picked',
  'w4.beat': 'Beat',
  'w4.everyBeat': 'Every beat',
  'w4.selected': '{count} selected · {pieces} pc',
  'w4.makeWave': 'Make a wave',
  'w4.waveFailed': 'Could not raise the wave',
  'w4.mixedLocation': 'Those orders are picked from two different godowns — choose one.',
  'w4.onWave': 'Already on a wave',
  'w4.waves': 'WAVES',
  'w4.wavesEmpty': 'No wave yet',
  'w4.wavePicked': '{picked} of {requested} pc picked',
  'w4.selectAll': 'Select all',
  'w4.clear': 'Clear',

  // ---------------------------------------------------------------- W5 picking sheet
  'w5.title': 'Picklist',
  'w5.progress': '{picked} of {total} picked',
  'w5.start': 'Start picking',
  'w5.startFailed': 'Could not start the sheet',
  'w5.startOffline': 'Starting a sheet needs a signal',
  'w5.picked': 'Picked',
  'w5.short': 'Short',
  'w5.shortReason': 'Why is it short?',
  'w5.shortReasons': 'Not on the rack · Damaged carton · Batch held back',
  'w5.reasonRack': 'Not on the rack',
  'w5.reasonDamaged': 'Damaged carton',
  'w5.reasonHeld': 'Batch held back',
  'w5.reasonOther': 'Something else',
  'w5.fefo': 'Older lot first · {batch}',
  'w5.linesLeft': '{count} lines not yet picked',
  'w5.linesLeft.one': '{count} line not yet picked',
  'w5.allPicked': 'Every line picked or short',
  /* Picking has no Save step (UX-00 section 9.4): this button goes to packing, so it says so. */
  'w5.confirm': 'Take it to packing',
  'w5.savedLine': 'Line saved on this phone',
  'w5.notStarted': 'This sheet has not been started',
  'w5.cancelIsManager': 'A wave is cancelled by the manager.',
  'w5.viewTodo': 'To pick',
  'w5.viewAll': 'Every line',
  'w5.bin': 'Requested {pieces} pc',
  'w5.enterPieces': 'Pieces picked',
  'w5.pickedAll': 'Picked in full',
  'w5.status': 'Sheet is {status}',
  'w5.offlineNote': 'Picks are saved on this phone and sent when there is a signal.',
  'w5.scanToPick': 'Scan a carton',

  // ---------------------------------------------------------------- W6 pack
  'w6.title': 'Pack',
  'w6.tab': 'To pack',
  'w6.ready': 'READY TO PACK',
  'w6.readyEmpty': 'Nothing picked and waiting',
  'w6.done': 'PACKED TODAY',
  'w6.doneEmpty': 'Nothing packed yet',
  'w6.packages': 'Cartons',
  'w6.weight': 'Weight in grams',
  'w6.packIt': 'Pack and bill',
  'w6.parkIt': 'Pack without a bill',
  'w6.confirmTitle': 'Pack {order}?',
  'w6.confirmBody':
    '{packages} cartons leave the godown for {shop}. The bill is issued in the same step and cannot be edited afterwards.',
  'w6.parkBody':
    '{packages} cartons leave the godown for {shop}. No bill yet — the desk bills it from the backlog.',
  'w6.packFailed': 'Could not pack it',
  'w6.packed': 'Packed',
  'w6.invoiceIssued': 'Bill {invoiceNo} issued',
  'w6.shortPacked': 'Short packed',
  'w6.openBill': 'Open the bill',
  'w6.printBill': 'Print the bill',
  'w6.billQueued': 'The bill is being drawn — try the print again in a moment',
  'w6.lines': 'WHAT GOES IN THE CARTONS',
  'w6.ordered': 'Ordered',
  'w6.packedQty': 'Packed',
  'w6.shortQty': 'Short',
  'w6.noBill': 'No bill yet',
  'w6.ewb': 'E-way bill number',
  'w6.ewbIsDesk': 'The e-way bill number is typed at the desk.',

  // ---------------------------------------------------------------- W7 load sheet
  'w7.title': 'Load',
  'w7.tab': 'Sheets',
  'w7.sheets': 'LOAD SHEETS',
  'w7.sheetsEmpty': 'No sheet yet',
  'w7.build': 'Build a sheet',
  'w7.vehicle': 'Vehicle',
  'w7.packedOrders': 'PACKED ORDERS',
  'w7.packedEmpty': 'Nothing packed and waiting for a vehicle',
  'w7.createFailed': 'Could not build the sheet',
  'w7.waitingApproval': 'Waiting for the manager',
  'w7.waitingBody':
    'A manager approves this sheet from the manager app. This screen unlocks the moment it lands.',
  'w7.approvedBy': 'Approved · {when}',
  'w7.countPackages': 'Count the cartons',
  'w7.countLabel': 'Cartons on the vehicle',
  'w7.expected': 'Expected {count}',
  'w7.countedWas': 'Counted {count}',
  'w7.variance': 'The count differs — say why',
  'w7.varianceNote': 'What is different?',
  'w7.confirm': 'Send the vehicle out',
  'w7.confirmTitle': 'Check out {vehicle}?',
  'w7.confirmBody':
    '{counted} cartons leave on {vehicle}. Stock moves to the vehicle and challan paper is issued. This cannot be undone.',
  'w7.confirmFailed': 'Could not check the vehicle out',
  'w7.confirmed': 'Vehicle checked out',
  'w7.challan': 'Challan {no}',
  'w7.printChallan': 'Print the challan',
  'w7.challanQueued': 'The challan is being drawn — try the print again in a moment',
  'w7.ewbRequired': 'An e-way bill is needed for this load. The desk types the number.',
  'w7.ewbNo': 'E-way bill {no}',
  'w7.lots': 'WHAT GOES ON THE VEHICLE',
  'w7.orders': 'ORDERS ON THIS SHEET',
  'w7.sourceOrder': 'For an order',
  'w7.sourceVan': 'Van stock',
  'w7.cancelIsManager': 'A sheet is cancelled by the manager.',
  'w7.status': 'Sheet is {status}',
  'w7.loadValue': 'Declared value',

  // ---------------------------------------------------------------- W9 van check-in
  'w9.title': 'Van check-in',
  'w9.tab': 'Check-in',
  'w9.body': 'Count what came back on the vehicle. The settlement itself is desk work.',
  'w9.expectedOnVan': 'EXPECTED ON THE VEHICLE',
  'w9.expectedEmpty': 'Nothing is loaded on this vehicle',
  'w9.countBack': 'Count back',
  'w9.countedBack': 'Counted {counted} · expected {expected}',
  'w9.short': 'Short {count} pc',
  'w9.over': 'Over {count} pc',
  'w9.match': 'Matches',
  'w9.moveBack': 'Move back to the godown',
  'w9.moveFailed': 'Could not move it back',
  'w9.moved': 'Moved back to the godown',
  'w9.settlementIsDesk': 'The money side of the trip is settled at the desk.',
  'w9.pieces': 'Pieces counted back',

  // ---------------------------------------------------------------- W8 stock
  'w8.title': 'Stock',
  'w8.tab': 'Stock',
  'w8c.tab': 'Counts',
  'w8.search': 'Search an item or a batch',
  'w8.allStock': 'All stock',
  'w8.nearExpiry': 'Near expiry only',
  'w8.rows': 'STOCK BY LOT',
  'w8.rowsEmpty': 'No stock at this location',
  'w8.onHand': 'On hand',
  'w8.reserved': 'Held',
  'w8.free': 'Free',
  'w8.adjust': 'Adjust',
  'w8.transfer': 'Move',
  'w8.adjustTitle': 'Adjust {item}',
  'w8.adjustQty': 'Pieces, + or −',
  'w8.adjustReason': 'Reason',
  'w8.reasonAdjustment': 'Correction',
  'w8.reasonDamage': 'Damaged',
  'w8.reasonExpiry': 'Written off, expired',
  'w8.reasonCycle': 'Count difference',
  'w8.reasonOpening': 'Opening stock',
  'w8.adjustNote': 'Note',
  'w8.adjustDo': 'Post the adjustment',
  'w8.adjustFailed': 'Could not post it',
  'w8.adjusted': 'Adjustment posted',
  'w8.transferTitle': 'Move {item}',
  'w8.transferTo': 'Move to',
  'w8.transferQty': 'Pieces to move',
  'w8.transferDo': 'Move the stock',
  'w8.transferFailed': 'Could not move it',
  'w8.transferred': 'Stock moved',
  'w8.ledger': 'LAST MOVEMENTS',
  'w8.ledgerEmpty': 'No movement recorded',
  'w8.reasonNeeded': 'Choose a reason',
  'w8.qtyNeeded': 'Enter a number of pieces',

  // cycle counts
  'w8c.title': 'Cycle counts',
  'w8c.open': 'Open a count',
  'w8c.counts': 'COUNTS',
  'w8c.countsEmpty': 'No count open',
  'w8c.countIt': 'Count it',
  'w8c.countTitle': 'Count {location}',
  'w8c.blind': 'Blind count: the expected figure is not on this screen.',
  'w8c.save': 'Save the count',
  'w8c.saved': 'Count saved',
  'w8c.saveFailed': 'Could not save the count',
  'w8c.openFailed': 'Could not open a count',
  'w8c.postIsDesk': 'The desk posts the differences into the ledger.',
  'w8c.counted': 'Counted',
  'w8c.notCounted': 'Not counted',
  'w8c.status': 'Count is {status}',
  'w8c.note': 'Note',

  // ---------------------------------------------------------------- W10 trips
  'w10.title': 'Trips',
  'w10.tab': 'Trips',
  'w10.trips': 'TRIPS',
  'w10.tripsEmpty': 'No trip today',
  'w10.stops': '{done} of {planned} stops',
  'w10.startLoading': 'Start loading',
  'w10.startFailed': 'Could not start loading',
  'w10.loading': 'Loading',
  'w10.depart': 'Send it off',
  'w10.departFailed': 'Could not send it off',

  // ---------------------------------------------------------------- W11 reservations
  'w11.title': 'Held for orders',
  'w11.tab': 'Held',
  'w11.rows': 'STOCK HELD',
  'w11.rowsEmpty': 'Nothing held',
  'w11.releaseIsDesk': 'A hold is freed at the desk.',
  'w11.forOrder': 'For {order}',
} as const
