import * as L from './lib.mjs'
import * as F from './flow.mjs'
L.wireTo('probe2')
const shop = await F.createShop('QA P7 Probe Two', { creditLimitPaise: 50_000_00 })
const o = await F.placeOrder(shop.id, [{ variantId: 'f71bf137-50de-7182-a0d9-c83f1a613a57', qty: 12 }, { variantId: 'af45e021-a167-7d3f-a8f0-60ab037214cb', qty: 24 }])
console.log('order', o.submitted.value.item.orderNo, o.submitted.value.item.state, o.submitted.value.item.totalPaise)
const pp = await F.pickAndPack([o.orderId])
console.log('invoices', pp.invoices.map((i) => [i.invoiceNo, i.totalPaise]))
console.log('pack reply', JSON.stringify(pp.invoices[0].packed).slice(0, 600))
const trip = await F.tripOut([{ retailerId: shop.id, invoiceIds: [pp.invoices[0].invoiceId] }], { floatPaise: 50000 })
console.log('trip', trip.tripId)
const d = await F.deliver(trip, trip.stops[0], pp.invoices[0].invoiceId)
console.log('deliver', JSON.stringify(d).slice(0, 700))
const c = await F.collect(trip, trip.stops[0], shop.id, 'cash', pp.invoices[0].totalPaise)
console.log('collect', JSON.stringify(c).slice(0, 900))
const s = await F.checkInAndSettle(trip)
console.log('return', JSON.stringify(s.ret).slice(0, 300))
console.log('preview', JSON.stringify(s.preview).slice(0, 1500))
console.log('settle', JSON.stringify(s.settle).slice(0, 800))
const dep = await F.deposit([c.receiptId])
console.log('deposit', JSON.stringify(dep).slice(0, 500))
console.log(JSON.stringify(await F.shopFigures(shop.id), null, 0))
